/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.api;

import com.officeintegrator.ApiException;
import com.officeintegrator.model.BasicErrorModel;
import com.officeintegrator.model.PlanDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OfficeIntegratorApi
 */
@Ignore
public class OfficeIntegratorApiTest {

    private final OfficeIntegratorApi api = new OfficeIntegratorApi();

    /**
     * 
     *
     * To retrieve the plan details including the API calls usage.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPlanDetailsTest() throws ApiException {
        PlanDetails response = api.getPlanDetails();

        // TODO: test validations
    }
}
