/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.api;

import com.officeintegrator.ApiException;
import com.officeintegrator.model.BasicErrorModel;
import com.officeintegrator.model.CreateDocumentResponse;
import com.officeintegrator.model.CreateSheetResponse;
import com.officeintegrator.model.DocumentInfo;
import java.io.File;
import com.officeintegrator.model.InlineResponse200;
import com.officeintegrator.model.InlineResponse2001;
import com.officeintegrator.model.InlineResponse2002;
import com.officeintegrator.model.PreviewSheetResponse;
import com.officeintegrator.model.SheetCallbackSettings;
import com.officeintegrator.model.SheetEditPermissions;
import com.officeintegrator.model.SheetEditorSettings;
import com.officeintegrator.model.SheetReadOnlyPermissions;
import com.officeintegrator.model.SheetSupportedLanguages;
import com.officeintegrator.model.SheetUserInfo;
import com.officeintegrator.model.ShowCallbackSettings;
import com.officeintegrator.model.Showofficeapiv1presentationEditorSettings;
import com.officeintegrator.model.UserInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SheetEditorApi
 */
@Ignore
public class SheetEditorApiTest {

    private final SheetEditorApi api = new SheetEditorApi();

    /**
     * 
     *
     * To create/edit a presentation in Zoho Show.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createPresentationTest() throws ApiException {
        File document = null;
        String url = null;
        ShowCallbackSettings callbackSettings = null;
        Showofficeapiv1presentationEditorSettings editorSettings = null;
        SheetEditPermissions permissions = null;
        DocumentInfo documentInfo = null;
        UserInfo userInfo = null;
        CreateDocumentResponse response = api.createPresentation(document, url, callbackSettings, editorSettings, permissions, documentInfo, userInfo);

        // TODO: test validations
    }
    /**
     * 
     *
     * To create a new document in Zoho Writer.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSpreadsheetTest() throws ApiException {
        File document = null;
        String url = null;
        SheetCallbackSettings callbackSettings = null;
        SheetEditorSettings editorSettings = null;
        SheetEditPermissions permissions = null;
        DocumentInfo documentInfo = null;
        SheetUserInfo userInfo = null;
        CreateSheetResponse response = api.createSpreadsheet(document, url, callbackSettings, editorSettings, permissions, documentInfo, userInfo);

        // TODO: test validations
    }
    /**
     * 
     *
     * To delete a particular document in Zoho Writer through a unique document id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSheetTest() throws ApiException {
        String documentId = null;
        InlineResponse2001 response = api.deleteSheet(documentId);

        // TODO: test validations
    }
    /**
     * 
     *
     * To delete a particular user session of in Zoho Sheet.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSheetSessionTest() throws ApiException {
        String sessionId = null;
        InlineResponse200 response = api.deleteSheetSession(sessionId);

        // TODO: test validations
    }
    /**
     * 
     *
     * To delete a particular presentation in Zoho Show through a unique document id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteShowTest() throws ApiException {
        String documentId = null;
        InlineResponse2002 response = api.deleteShow(documentId);

        // TODO: test validations
    }
    /**
     * 
     *
     * To delete a particular user session of in Zoho Show.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteShowSessionTest() throws ApiException {
        String sessionId = null;
        InlineResponse200 response = api.deleteShowSession(sessionId);

        // TODO: test validations
    }
    /**
     * 
     *
     * To open a spreadsheet in preview or read-only mode in Zoho Sheet.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void previewSpreadsheetTest() throws ApiException {
        File document = null;
        String url = null;
        SheetSupportedLanguages language = null;
        SheetReadOnlyPermissions permissions = null;
        PreviewSheetResponse response = api.previewSpreadsheet(document, url, language, permissions);

        // TODO: test validations
    }
}
