/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.api;

import com.officeintegrator.ApiException;
import com.officeintegrator.model.BasicErrorModel;
import java.io.File;
import com.officeintegrator.model.PreviewResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShowEditorApi
 */
@Ignore
public class ShowEditorApiTest {

    private final ShowEditorApi api = new ShowEditorApi();

    /**
     * 
     *
     * To open a presentation in preview or read-only mode in Zoho Sheet.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void previewPresentationTest() throws ApiException {
        File document = null;
        String url = null;
        String language = null;
        PreviewResponse response = api.previewPresentation(document, url, language);

        // TODO: test validations
    }
}
