/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.api;

import com.officeintegrator.ApiException;
import com.officeintegrator.model.BasicErrorModel;
import com.officeintegrator.model.CreateDocumentResponse;
import com.officeintegrator.model.DocumentDefaults;
import com.officeintegrator.model.DocumentInfo;
import java.io.File;
import com.officeintegrator.model.GetMergeFieldsReponse;
import com.officeintegrator.model.MailMergeWebHookSettings;
import com.officeintegrator.model.MergeAndDeliverReponse;
import com.officeintegrator.model.UserInfo;
import com.officeintegrator.model.WriterCallbackSettings;
import com.officeintegrator.model.WriterEditorSettings;
import com.officeintegrator.model.WriterMergeExportFormat;
import com.officeintegrator.model.WriterPermissions;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WriterMergeApi
 */
@Ignore
public class WriterMergeApiTest {

    private final WriterMergeApi api = new WriterMergeApi();

    /**
     * 
     *
     * To create a new template in Zoho Writer.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDocumentTemplateTest() throws ApiException {
        File document = null;
        String url = null;
        WriterCallbackSettings callbackSettings = null;
        DocumentDefaults documentDefaults = null;
        WriterEditorSettings editorSettings = null;
        WriterPermissions permissions = null;
        DocumentInfo documentInfo = null;
        UserInfo userInfo = null;
        File mergeDataCsvContent = null;
        File mergeDataJsonContent = null;
        CreateDocumentResponse response = api.createDocumentTemplate(document, url, callbackSettings, documentDefaults, editorSettings, permissions, documentInfo, userInfo, mergeDataCsvContent, mergeDataJsonContent);

        // TODO: test validations
    }
    /**
     * 
     *
     * To get the list of available merge fields present in the document.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDocumentMergeFieldsTest() throws ApiException {
        File fileContent = null;
        String fileUrl = null;
        GetMergeFieldsReponse response = api.getDocumentMergeFields(fileContent, fileUrl);

        // TODO: test validations
    }
    /**
     * 
     *
     * To send or post the merged document to the given webhook URL.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mergeAndDeliverDocumentTest() throws ApiException {
        WriterMergeExportFormat outputFormat = null;
        File fileContent = null;
        String fileUrl = null;
        MailMergeWebHookSettings webhook = null;
        String mergeTo = null;
        Map<String, Object> mergeData = null;
        File mergeDataCsvContent = null;
        File mergeDataJsonContent = null;
        String mergeDataCsvUrl = null;
        String mergeDataJsonUrl = null;
        String password = null;
        MergeAndDeliverReponse response = api.mergeAndDeliverDocument(outputFormat, fileContent, fileUrl, webhook, mergeTo, mergeData, mergeDataCsvContent, mergeDataJsonContent, mergeDataCsvUrl, mergeDataJsonUrl, password);

        // TODO: test validations
    }
    /**
     * 
     *
     * This API will allow you to generate documents and merge them.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mergeDocumentTest() throws ApiException {
        WriterMergeExportFormat outputFormat = null;
        File fileContent = null;
        String fileUrl = null;
        Map<String, Object> mergeData = null;
        File mergeDataCsvContent = null;
        File mergeDataJsonContent = null;
        String mergeDataCsvUrl = null;
        String mergeDataJsonUrl = null;
        String password = null;
        File response = api.mergeDocument(outputFormat, fileContent, fileUrl, mergeData, mergeDataCsvContent, mergeDataJsonContent, mergeDataCsvUrl, mergeDataJsonUrl, password);

        // TODO: test validations
    }
}
