/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.api;

import com.officeintegrator.ApiException;
import com.officeintegrator.model.BasicErrorModel;
import com.officeintegrator.model.CompareDocumentResponse;
import com.officeintegrator.model.CreateDocumentResponse;
import com.officeintegrator.model.DocumentDefaults;
import com.officeintegrator.model.DocumentInfo;
import java.io.File;
import com.officeintegrator.model.InlineResponse200;
import com.officeintegrator.model.InlineResponse2001;
import com.officeintegrator.model.PreviewResponse;
import com.officeintegrator.model.UIOptions;
import com.officeintegrator.model.UserInfo;
import com.officeintegrator.model.WriterCallbackSettings;
import com.officeintegrator.model.WriterEditorSettings;
import com.officeintegrator.model.WriterPermissions;
import com.officeintegrator.model.WriterSupportedLanguages;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WriterEditorApi
 */
@Ignore
public class WriterEditorApiTest {

    private final WriterEditorApi api = new WriterEditorApi();

    /**
     * 
     *
     * To compare two versions of a document and highlight the difference in text.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void compareDocumentTest() throws ApiException {
        File document1 = null;
        String url1 = null;
        File document2 = null;
        String url2 = null;
        String title = null;
        WriterSupportedLanguages lang = null;
        CompareDocumentResponse response = api.compareDocument(document1, url1, document2, url2, title, lang);

        // TODO: test validations
    }
    /**
     * 
     *
     * To create a new document in Zoho Writer.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDocumentTest() throws ApiException {
        File document = null;
        String url = null;
        WriterCallbackSettings callbackSettings = null;
        DocumentDefaults documentDefaults = null;
        WriterEditorSettings editorSettings = null;
        WriterPermissions permissions = null;
        DocumentInfo documentInfo = null;
        UserInfo userInfo = null;
        UIOptions uiOptions = null;
        CreateDocumentResponse response = api.createDocument(document, url, callbackSettings, documentDefaults, editorSettings, permissions, documentInfo, userInfo, uiOptions);

        // TODO: test validations
    }
    /**
     * 
     *
     * To delete a particular document in Zoho Writer through a unique document id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDocumentTest() throws ApiException {
        String documentId = null;
        InlineResponse2001 response = api.deleteDocument(documentId);

        // TODO: test validations
    }
    /**
     * 
     *
     * To delete a user session of a particular document in Zoho Writer.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteWriterSessionTest() throws ApiException {
        String sessionId = null;
        InlineResponse200 response = api.deleteWriterSession(sessionId);

        // TODO: test validations
    }
    /**
     * 
     *
     * To create a new document in Zoho Writer.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void previewDocumentTest() throws ApiException {
        File document = null;
        String url = null;
        WriterSupportedLanguages lang = null;
        PreviewResponse response = api.previewDocument(document, url, lang);

        // TODO: test validations
    }
}
