/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.api;

import com.officeintegrator.ApiException;
import com.officeintegrator.model.BasicErrorModel;
import java.io.File;
import com.officeintegrator.model.OutputOptions;
import com.officeintegrator.model.WatermarkSettings;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WriterConversionApi
 */
@Ignore
public class WriterConversionApiTest {

    private final WriterConversionApi api = new WriterConversionApi();

    /**
     * 
     *
     * To convert a document to any Writer supported format (.docx, .doc, .pdf, .zdoc etc.)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void convertDocumentTest() throws ApiException {
        File document = null;
        String url = null;
        OutputOptions outputOptions = null;
        String password = null;
        File response = api.convertDocument(document, url, outputOptions, password);

        // TODO: test validations
    }
    /**
     * 
     *
     * Using this API, you can provide the watermark details in the form of text.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void watermarkDocumentTest() throws ApiException {
        File document = null;
        String url = null;
        WatermarkSettings watermarkSettings = null;
        File response = api.watermarkDocument(document, url, watermarkSettings);

        // TODO: test validations
    }
}
