/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.WatermarkSettings;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * Body8
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class Body8 {
  @SerializedName("document")
  private File document = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("watermark_settings")
  private WatermarkSettings watermarkSettings = null;

  public Body8 document(File document) {
    this.document = document;
    return this;
  }

   /**
   * File to be open in Zoho Writer
   * @return document
  **/
  @Schema(description = "File to be open in Zoho Writer")
  public File getDocument() {
    return document;
  }

  public void setDocument(File document) {
    this.document = document;
  }

  public Body8 url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Publicly accessible document link to import file to open in Zoho Writer
   * @return url
  **/
  @Schema(example = "https://s3.console.aws.amazon.com/s3/object/pkr3/writerfile.docx", description = "Publicly accessible document link to import file to open in Zoho Writer")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Body8 watermarkSettings(WatermarkSettings watermarkSettings) {
    this.watermarkSettings = watermarkSettings;
    return this;
  }

   /**
   * Get watermarkSettings
   * @return watermarkSettings
  **/
  @Schema(description = "")
  public WatermarkSettings getWatermarkSettings() {
    return watermarkSettings;
  }

  public void setWatermarkSettings(WatermarkSettings watermarkSettings) {
    this.watermarkSettings = watermarkSettings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body8 body8 = (Body8) o;
    return Objects.equals(this.document, body8.document) &&
        Objects.equals(this.url, body8.url) &&
        Objects.equals(this.watermarkSettings, body8.watermarkSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(document), url, watermarkSettings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body8 {\n");
    
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    watermarkSettings: ").append(toIndentedString(watermarkSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
