/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.WriterSupportedLanguages;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * Body2
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class Body2 {
  @SerializedName("document1")
  private File document1 = null;

  @SerializedName("url1")
  private String url1 = "";

  @SerializedName("document2")
  private File document2 = null;

  @SerializedName("url2")
  private String url2 = "";

  @SerializedName("title")
  private String title = "";

  @SerializedName("lang")
  private WriterSupportedLanguages lang = null;

  public Body2 document1(File document1) {
    this.document1 = document1;
    return this;
  }

   /**
   * if the 1st version of the input file is from your local drive or desktop.
   * @return document1
  **/
  @Schema(description = "if the 1st version of the input file is from your local drive or desktop.")
  public File getDocument1() {
    return document1;
  }

  public void setDocument1(File document1) {
    this.document1 = document1;
  }

  public Body2 url1(String url1) {
    this.url1 = url1;
    return this;
  }

   /**
   * if the 1st version of the input file is from a publicly accessible Web URL.
   * @return url1
  **/
  @Schema(example = "https://s3.console.aws.amazon.com/s3/object/pkr3/writerfile1.docx", description = "if the 1st version of the input file is from a publicly accessible Web URL.")
  public String getUrl1() {
    return url1;
  }

  public void setUrl1(String url1) {
    this.url1 = url1;
  }

  public Body2 document2(File document2) {
    this.document2 = document2;
    return this;
  }

   /**
   * if the 2nd version of the input file is from your local drive or desktop.
   * @return document2
  **/
  @Schema(description = "if the 2nd version of the input file is from your local drive or desktop.")
  public File getDocument2() {
    return document2;
  }

  public void setDocument2(File document2) {
    this.document2 = document2;
  }

  public Body2 url2(String url2) {
    this.url2 = url2;
    return this;
  }

   /**
   * if the 2nd version of the input file is from a publicly accessible Web URL.
   * @return url2
  **/
  @Schema(example = "https://s3.console.aws.amazon.com/s3/object/pkr3/writerfile2.docx", description = "if the 2nd version of the input file is from a publicly accessible Web URL.")
  public String getUrl2() {
    return url2;
  }

  public void setUrl2(String url2) {
    this.url2 = url2;
  }

  public Body2 title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Defines document title of the 2 versions of comparison files. Note - If the user fails to provide value for &#x27;title&#x27; parameter, Zoho Writer will combine the names from &#x27;document1&#x27; &amp; &#x27;document2&#x27; parameters, and replace it as the title
   * @return title
  **/
  @Schema(description = "Defines document title of the 2 versions of comparison files. Note - If the user fails to provide value for 'title' parameter, Zoho Writer will combine the names from 'document1' & 'document2' parameters, and replace it as the title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Body2 lang(WriterSupportedLanguages lang) {
    this.lang = lang;
    return this;
  }

   /**
   * Get lang
   * @return lang
  **/
  @Schema(description = "")
  public WriterSupportedLanguages getLang() {
    return lang;
  }

  public void setLang(WriterSupportedLanguages lang) {
    this.lang = lang;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body2 body2 = (Body2) o;
    return Objects.equals(this.document1, body2.document1) &&
        Objects.equals(this.url1, body2.url1) &&
        Objects.equals(this.document2, body2.document2) &&
        Objects.equals(this.url2, body2.url2) &&
        Objects.equals(this.title, body2.title) &&
        Objects.equals(this.lang, body2.lang);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(document1), url1, Objects.hashCode(document2), url2, title, lang);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body2 {\n");
    
    sb.append("    document1: ").append(toIndentedString(document1)).append("\n");
    sb.append("    url1: ").append(toIndentedString(url1)).append("\n");
    sb.append("    document2: ").append(toIndentedString(document2)).append("\n");
    sb.append("    url2: ").append(toIndentedString(url2)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
