/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.DocumentInfo;
import com.officeintegrator.model.SheetEditPermissions;
import com.officeintegrator.model.ShowCallbackSettings;
import com.officeintegrator.model.Showofficeapiv1presentationEditorSettings;
import com.officeintegrator.model.UserInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * Body11
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class Body11 {
  @SerializedName("document")
  private File document = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("callback_settings")
  private ShowCallbackSettings callbackSettings = null;

  @SerializedName("editor_settings")
  private Showofficeapiv1presentationEditorSettings editorSettings = null;

  @SerializedName("permissions")
  private SheetEditPermissions permissions = null;

  @SerializedName("document_info")
  private DocumentInfo documentInfo = null;

  @SerializedName("user_info")
  private UserInfo userInfo = null;

  public Body11 document(File document) {
    this.document = document;
    return this;
  }

   /**
   * if the input file is from your local drive or desktop.
   * @return document
  **/
  @Schema(description = "if the input file is from your local drive or desktop.")
  public File getDocument() {
    return document;
  }

  public void setDocument(File document) {
    this.document = document;
  }

  public Body11 url(String url) {
    this.url = url;
    return this;
  }

   /**
   * if the input file is from a publicly accessible Web URL.
   * @return url
  **/
  @Schema(example = "https://s3.console.aws.amazon.com/s3/object/pkr3/sheetfile.xlsx", description = "if the input file is from a publicly accessible Web URL.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Body11 callbackSettings(ShowCallbackSettings callbackSettings) {
    this.callbackSettings = callbackSettings;
    return this;
  }

   /**
   * Get callbackSettings
   * @return callbackSettings
  **/
  @Schema(required = true, description = "")
  public ShowCallbackSettings getCallbackSettings() {
    return callbackSettings;
  }

  public void setCallbackSettings(ShowCallbackSettings callbackSettings) {
    this.callbackSettings = callbackSettings;
  }

  public Body11 editorSettings(Showofficeapiv1presentationEditorSettings editorSettings) {
    this.editorSettings = editorSettings;
    return this;
  }

   /**
   * Get editorSettings
   * @return editorSettings
  **/
  @Schema(description = "")
  public Showofficeapiv1presentationEditorSettings getEditorSettings() {
    return editorSettings;
  }

  public void setEditorSettings(Showofficeapiv1presentationEditorSettings editorSettings) {
    this.editorSettings = editorSettings;
  }

  public Body11 permissions(SheetEditPermissions permissions) {
    this.permissions = permissions;
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @Schema(description = "")
  public SheetEditPermissions getPermissions() {
    return permissions;
  }

  public void setPermissions(SheetEditPermissions permissions) {
    this.permissions = permissions;
  }

  public Body11 documentInfo(DocumentInfo documentInfo) {
    this.documentInfo = documentInfo;
    return this;
  }

   /**
   * Get documentInfo
   * @return documentInfo
  **/
  @Schema(description = "")
  public DocumentInfo getDocumentInfo() {
    return documentInfo;
  }

  public void setDocumentInfo(DocumentInfo documentInfo) {
    this.documentInfo = documentInfo;
  }

  public Body11 userInfo(UserInfo userInfo) {
    this.userInfo = userInfo;
    return this;
  }

   /**
   * Get userInfo
   * @return userInfo
  **/
  @Schema(description = "")
  public UserInfo getUserInfo() {
    return userInfo;
  }

  public void setUserInfo(UserInfo userInfo) {
    this.userInfo = userInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body11 body11 = (Body11) o;
    return Objects.equals(this.document, body11.document) &&
        Objects.equals(this.url, body11.url) &&
        Objects.equals(this.callbackSettings, body11.callbackSettings) &&
        Objects.equals(this.editorSettings, body11.editorSettings) &&
        Objects.equals(this.permissions, body11.permissions) &&
        Objects.equals(this.documentInfo, body11.documentInfo) &&
        Objects.equals(this.userInfo, body11.userInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(document), url, callbackSettings, editorSettings, permissions, documentInfo, userInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body11 {\n");
    
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    callbackSettings: ").append(toIndentedString(callbackSettings)).append("\n");
    sb.append("    editorSettings: ").append(toIndentedString(editorSettings)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    documentInfo: ").append(toIndentedString(documentInfo)).append("\n");
    sb.append("    userInfo: ").append(toIndentedString(userInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
