/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.DocumentDefaults;
import com.officeintegrator.model.DocumentInfo;
import com.officeintegrator.model.UIOptions;
import com.officeintegrator.model.UserInfo;
import com.officeintegrator.model.WriterCallbackSettings;
import com.officeintegrator.model.WriterEditorSettings;
import com.officeintegrator.model.WriterPermissions;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * Body
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class Body {
  @SerializedName("document")
  private File document = null;

  @SerializedName("url")
  private String url = "";

  @SerializedName("callback_settings")
  private WriterCallbackSettings callbackSettings = null;

  @SerializedName("document_defaults")
  private DocumentDefaults documentDefaults = null;

  @SerializedName("editor_settings")
  private WriterEditorSettings editorSettings = null;

  @SerializedName("permissions")
  private WriterPermissions permissions = null;

  @SerializedName("document_info")
  private DocumentInfo documentInfo = null;

  @SerializedName("user_info")
  private UserInfo userInfo = null;

  @SerializedName("ui_options")
  private UIOptions uiOptions = null;

  public Body document(File document) {
    this.document = document;
    return this;
  }

   /**
   * File to be open in Zoho Writer
   * @return document
  **/
  @Schema(description = "File to be open in Zoho Writer")
  public File getDocument() {
    return document;
  }

  public void setDocument(File document) {
    this.document = document;
  }

  public Body url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Publicly accessible document link to import file to open in Zoho Writer
   * @return url
  **/
  @Schema(example = "https://s3.console.aws.amazon.com/s3/object/pkr3/writerfile.docx", description = "Publicly accessible document link to import file to open in Zoho Writer")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Body callbackSettings(WriterCallbackSettings callbackSettings) {
    this.callbackSettings = callbackSettings;
    return this;
  }

   /**
   * Get callbackSettings
   * @return callbackSettings
  **/
  @Schema(required = true, description = "")
  public WriterCallbackSettings getCallbackSettings() {
    return callbackSettings;
  }

  public void setCallbackSettings(WriterCallbackSettings callbackSettings) {
    this.callbackSettings = callbackSettings;
  }

  public Body documentDefaults(DocumentDefaults documentDefaults) {
    this.documentDefaults = documentDefaults;
    return this;
  }

   /**
   * Get documentDefaults
   * @return documentDefaults
  **/
  @Schema(description = "")
  public DocumentDefaults getDocumentDefaults() {
    return documentDefaults;
  }

  public void setDocumentDefaults(DocumentDefaults documentDefaults) {
    this.documentDefaults = documentDefaults;
  }

  public Body editorSettings(WriterEditorSettings editorSettings) {
    this.editorSettings = editorSettings;
    return this;
  }

   /**
   * Get editorSettings
   * @return editorSettings
  **/
  @Schema(description = "")
  public WriterEditorSettings getEditorSettings() {
    return editorSettings;
  }

  public void setEditorSettings(WriterEditorSettings editorSettings) {
    this.editorSettings = editorSettings;
  }

  public Body permissions(WriterPermissions permissions) {
    this.permissions = permissions;
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @Schema(description = "")
  public WriterPermissions getPermissions() {
    return permissions;
  }

  public void setPermissions(WriterPermissions permissions) {
    this.permissions = permissions;
  }

  public Body documentInfo(DocumentInfo documentInfo) {
    this.documentInfo = documentInfo;
    return this;
  }

   /**
   * Get documentInfo
   * @return documentInfo
  **/
  @Schema(description = "")
  public DocumentInfo getDocumentInfo() {
    return documentInfo;
  }

  public void setDocumentInfo(DocumentInfo documentInfo) {
    this.documentInfo = documentInfo;
  }

  public Body userInfo(UserInfo userInfo) {
    this.userInfo = userInfo;
    return this;
  }

   /**
   * Get userInfo
   * @return userInfo
  **/
  @Schema(description = "")
  public UserInfo getUserInfo() {
    return userInfo;
  }

  public void setUserInfo(UserInfo userInfo) {
    this.userInfo = userInfo;
  }

  public Body uiOptions(UIOptions uiOptions) {
    this.uiOptions = uiOptions;
    return this;
  }

   /**
   * Get uiOptions
   * @return uiOptions
  **/
  @Schema(description = "")
  public UIOptions getUiOptions() {
    return uiOptions;
  }

  public void setUiOptions(UIOptions uiOptions) {
    this.uiOptions = uiOptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body body = (Body) o;
    return Objects.equals(this.document, body.document) &&
        Objects.equals(this.url, body.url) &&
        Objects.equals(this.callbackSettings, body.callbackSettings) &&
        Objects.equals(this.documentDefaults, body.documentDefaults) &&
        Objects.equals(this.editorSettings, body.editorSettings) &&
        Objects.equals(this.permissions, body.permissions) &&
        Objects.equals(this.documentInfo, body.documentInfo) &&
        Objects.equals(this.userInfo, body.userInfo) &&
        Objects.equals(this.uiOptions, body.uiOptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(document), url, callbackSettings, documentDefaults, editorSettings, permissions, documentInfo, userInfo, uiOptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body {\n");
    
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    callbackSettings: ").append(toIndentedString(callbackSettings)).append("\n");
    sb.append("    documentDefaults: ").append(toIndentedString(documentDefaults)).append("\n");
    sb.append("    editorSettings: ").append(toIndentedString(editorSettings)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    documentInfo: ").append(toIndentedString(documentInfo)).append("\n");
    sb.append("    userInfo: ").append(toIndentedString(userInfo)).append("\n");
    sb.append("    uiOptions: ").append(toIndentedString(uiOptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
