/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * Body4
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class Body4 {
  @SerializedName("file_content")
  private File fileContent = null;

  @SerializedName("file_url")
  private String fileUrl = "";

  public Body4 fileContent(File fileContent) {
    this.fileContent = fileContent;
    return this;
  }

   /**
   * if the input file is from your local drive or desktop.
   * @return fileContent
  **/
  @Schema(description = "if the input file is from your local drive or desktop.")
  public File getFileContent() {
    return fileContent;
  }

  public void setFileContent(File fileContent) {
    this.fileContent = fileContent;
  }

  public Body4 fileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
    return this;
  }

   /**
   * if the input file is from a publicly accessible Web URL.
   * @return fileUrl
  **/
  @Schema(example = "https://s3.console.aws.amazon.com/s3/object/pkr3/writerfile.docx", description = "if the input file is from a publicly accessible Web URL.")
  public String getFileUrl() {
    return fileUrl;
  }

  public void setFileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body4 body4 = (Body4) o;
    return Objects.equals(this.fileContent, body4.fileContent) &&
        Objects.equals(this.fileUrl, body4.fileUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(fileContent), fileUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body4 {\n");
    
    sb.append("    fileContent: ").append(toIndentedString(fileContent)).append("\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
