/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * Body12
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class Body12 {
  @SerializedName("document")
  private File document = null;

  @SerializedName("url")
  private String url = null;

  /**
   * Language in which the editor interface to open in Writer
   */
  @JsonAdapter(LanguageEnum.Adapter.class)
  public enum LanguageEnum {
    DA("da"),
    DE("de"),
    ES("es"),
    FR("fr"),
    HU("hu"),
    IT("it"),
    JA("ja"),
    NL("nl"),
    PL("pl"),
    PT("pt"),
    RU("ru"),
    SV("sv"),
    TR("tr"),
    ZH("zh"),
    ZH_CN("zh_CN"),
    VI("vi"),
    CS("cs"),
    EL("el"),
    ET("et"),
    FI("fi"),
    HR("hr"),
    KO("ko"),
    LT("lt"),
    SK("sk"),
    TH("th"),
    UK("uk"),
    BG("bg"),
    CA("ca"),
    FALSE("false"),
    RO("ro"),
    AR("ar"),
    IW("iw"),
    UR("ur");

    private String value;

    LanguageEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static LanguageEnum fromValue(String text) {
      for (LanguageEnum b : LanguageEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<LanguageEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LanguageEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LanguageEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return LanguageEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("language")
  private LanguageEnum language = null;

  public Body12 document(File document) {
    this.document = document;
    return this;
  }

   /**
   * if the input file is from your local drive or desktop.
   * @return document
  **/
  @Schema(description = "if the input file is from your local drive or desktop.")
  public File getDocument() {
    return document;
  }

  public void setDocument(File document) {
    this.document = document;
  }

  public Body12 url(String url) {
    this.url = url;
    return this;
  }

   /**
   * if the input file is from a publicly accessible Web URL.
   * @return url
  **/
  @Schema(example = "https://s3.console.aws.amazon.com/s3/object/pkr3/sheetfile.xlsx", description = "if the input file is from a publicly accessible Web URL.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Body12 language(LanguageEnum language) {
    this.language = language;
    return this;
  }

   /**
   * Language in which the editor interface to open in Writer
   * @return language
  **/
  @Schema(description = "Language in which the editor interface to open in Writer")
  public LanguageEnum getLanguage() {
    return language;
  }

  public void setLanguage(LanguageEnum language) {
    this.language = language;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body12 body12 = (Body12) o;
    return Objects.equals(this.document, body12.document) &&
        Objects.equals(this.url, body12.url) &&
        Objects.equals(this.language, body12.language);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(document), url, language);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body12 {\n");
    
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
