/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.SheetReadOnlyPermissions;
import com.officeintegrator.model.SheetSupportedLanguages;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * Body10
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class Body10 {
  @SerializedName("document")
  private File document = null;

  @SerializedName("url")
  private String url = "";

  @SerializedName("language")
  private SheetSupportedLanguages language = null;

  @SerializedName("permissions")
  private SheetReadOnlyPermissions permissions = null;

  public Body10 document(File document) {
    this.document = document;
    return this;
  }

   /**
   * if the input file is from your local drive or desktop.
   * @return document
  **/
  @Schema(description = "if the input file is from your local drive or desktop.")
  public File getDocument() {
    return document;
  }

  public void setDocument(File document) {
    this.document = document;
  }

  public Body10 url(String url) {
    this.url = url;
    return this;
  }

   /**
   * if the input file is from a publicly accessible Web URL.
   * @return url
  **/
  @Schema(example = "https://s3.console.aws.amazon.com/s3/object/pkr3/sheetfile.xlsx", description = "if the input file is from a publicly accessible Web URL.")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Body10 language(SheetSupportedLanguages language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(description = "")
  public SheetSupportedLanguages getLanguage() {
    return language;
  }

  public void setLanguage(SheetSupportedLanguages language) {
    this.language = language;
  }

  public Body10 permissions(SheetReadOnlyPermissions permissions) {
    this.permissions = permissions;
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @Schema(description = "")
  public SheetReadOnlyPermissions getPermissions() {
    return permissions;
  }

  public void setPermissions(SheetReadOnlyPermissions permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body10 body10 = (Body10) o;
    return Objects.equals(this.document, body10.document) &&
        Objects.equals(this.url, body10.url) &&
        Objects.equals(this.language, body10.language) &&
        Objects.equals(this.permissions, body10.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(document), url, language, permissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body10 {\n");
    
    sb.append("    document: ").append(toIndentedString(document)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
