/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.MailMergeWebHookSettings;
import com.officeintegrator.model.WriterMergeExportFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * Body6
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class Body6 {
  @SerializedName("output_format")
  private WriterMergeExportFormat outputFormat = null;

  @SerializedName("file_content")
  private File fileContent = null;

  @SerializedName("file_url")
  private String fileUrl = null;

  @SerializedName("webhook")
  private MailMergeWebHookSettings webhook = null;

  /**
   * Supported merge types are separatedoc and singledoc. Specify in which type you would like to merge the document.
   */
  @JsonAdapter(MergeToEnum.Adapter.class)
  public enum MergeToEnum {
    SEPARATEDOC("separatedoc"),
    SINGLEDOC("singledoc");

    private String value;

    MergeToEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static MergeToEnum fromValue(String text) {
      for (MergeToEnum b : MergeToEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<MergeToEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MergeToEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MergeToEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return MergeToEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("merge_to")
  private MergeToEnum mergeTo = null;

  @SerializedName("merge_data")
  private Map<String, Object> mergeData = null;

  @SerializedName("merge_data_csv_content")
  private File mergeDataCsvContent = null;

  @SerializedName("merge_data_json_content")
  private File mergeDataJsonContent = null;

  @SerializedName("merge_data_csv_url")
  private String mergeDataCsvUrl = "";

  @SerializedName("merge_data_json_url")
  private String mergeDataJsonUrl = "";

  @SerializedName("password")
  private String password = null;

  public Body6 outputFormat(WriterMergeExportFormat outputFormat) {
    this.outputFormat = outputFormat;
    return this;
  }

   /**
   * Get outputFormat
   * @return outputFormat
  **/
  @Schema(description = "")
  public WriterMergeExportFormat getOutputFormat() {
    return outputFormat;
  }

  public void setOutputFormat(WriterMergeExportFormat outputFormat) {
    this.outputFormat = outputFormat;
  }

  public Body6 fileContent(File fileContent) {
    this.fileContent = fileContent;
    return this;
  }

   /**
   * if the input file is from your local drive or desktop.
   * @return fileContent
  **/
  @Schema(description = "if the input file is from your local drive or desktop.")
  public File getFileContent() {
    return fileContent;
  }

  public void setFileContent(File fileContent) {
    this.fileContent = fileContent;
  }

  public Body6 fileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
    return this;
  }

   /**
   * if the input file is from a publicly accessible Web URL.
   * @return fileUrl
  **/
  @Schema(example = "https://s3.console.aws.amazon.com/s3/object/pkr3/writerfile.docx", description = "if the input file is from a publicly accessible Web URL.")
  public String getFileUrl() {
    return fileUrl;
  }

  public void setFileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
  }

  public Body6 webhook(MailMergeWebHookSettings webhook) {
    this.webhook = webhook;
    return this;
  }

   /**
   * Get webhook
   * @return webhook
  **/
  @Schema(required = true, description = "")
  public MailMergeWebHookSettings getWebhook() {
    return webhook;
  }

  public void setWebhook(MailMergeWebHookSettings webhook) {
    this.webhook = webhook;
  }

  public Body6 mergeTo(MergeToEnum mergeTo) {
    this.mergeTo = mergeTo;
    return this;
  }

   /**
   * Supported merge types are separatedoc and singledoc. Specify in which type you would like to merge the document.
   * @return mergeTo
  **/
  @Schema(description = "Supported merge types are separatedoc and singledoc. Specify in which type you would like to merge the document.")
  public MergeToEnum getMergeTo() {
    return mergeTo;
  }

  public void setMergeTo(MergeToEnum mergeTo) {
    this.mergeTo = mergeTo;
  }

  public Body6 mergeData(Map<String, Object> mergeData) {
    this.mergeData = mergeData;
    return this;
  }

  public Body6 putMergeDataItem(String key, Object mergeDataItem) {
    if (this.mergeData == null) {
      this.mergeData = new HashMap<String, Object>();
    }
    this.mergeData.put(key, mergeDataItem);
    return this;
  }

   /**
   * Pass a String value through &#x27;data&#x27; key as JSON Array.
   * @return mergeData
  **/
  @Schema(description = "Pass a String value through 'data' key as JSON Array.")
  public Map<String, Object> getMergeData() {
    return mergeData;
  }

  public void setMergeData(Map<String, Object> mergeData) {
    this.mergeData = mergeData;
  }

  public Body6 mergeDataCsvContent(File mergeDataCsvContent) {
    this.mergeDataCsvContent = mergeDataCsvContent;
    return this;
  }

   /**
   * Provide the required csv content in your API request body.
   * @return mergeDataCsvContent
  **/
  @Schema(description = "Provide the required csv content in your API request body.")
  public File getMergeDataCsvContent() {
    return mergeDataCsvContent;
  }

  public void setMergeDataCsvContent(File mergeDataCsvContent) {
    this.mergeDataCsvContent = mergeDataCsvContent;
  }

  public Body6 mergeDataJsonContent(File mergeDataJsonContent) {
    this.mergeDataJsonContent = mergeDataJsonContent;
    return this;
  }

   /**
   * Provide the required json content in your API request body.
   * @return mergeDataJsonContent
  **/
  @Schema(description = "Provide the required json content in your API request body.")
  public File getMergeDataJsonContent() {
    return mergeDataJsonContent;
  }

  public void setMergeDataJsonContent(File mergeDataJsonContent) {
    this.mergeDataJsonContent = mergeDataJsonContent;
  }

  public Body6 mergeDataCsvUrl(String mergeDataCsvUrl) {
    this.mergeDataCsvUrl = mergeDataCsvUrl;
    return this;
  }

   /**
   * Provide the required csv url in your API request body.
   * @return mergeDataCsvUrl
  **/
  @Schema(description = "Provide the required csv url in your API request body.")
  public String getMergeDataCsvUrl() {
    return mergeDataCsvUrl;
  }

  public void setMergeDataCsvUrl(String mergeDataCsvUrl) {
    this.mergeDataCsvUrl = mergeDataCsvUrl;
  }

  public Body6 mergeDataJsonUrl(String mergeDataJsonUrl) {
    this.mergeDataJsonUrl = mergeDataJsonUrl;
    return this;
  }

   /**
   * Provide the required json url in your API request body.
   * @return mergeDataJsonUrl
  **/
  @Schema(description = "Provide the required json url in your API request body.")
  public String getMergeDataJsonUrl() {
    return mergeDataJsonUrl;
  }

  public void setMergeDataJsonUrl(String mergeDataJsonUrl) {
    this.mergeDataJsonUrl = mergeDataJsonUrl;
  }

  public Body6 password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Specify a password if you would like to protect the merged document.
   * @return password
  **/
  @Schema(example = "ax$123@sdc", description = "Specify a password if you would like to protect the merged document.")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body6 body6 = (Body6) o;
    return Objects.equals(this.outputFormat, body6.outputFormat) &&
        Objects.equals(this.fileContent, body6.fileContent) &&
        Objects.equals(this.fileUrl, body6.fileUrl) &&
        Objects.equals(this.webhook, body6.webhook) &&
        Objects.equals(this.mergeTo, body6.mergeTo) &&
        Objects.equals(this.mergeData, body6.mergeData) &&
        Objects.equals(this.mergeDataCsvContent, body6.mergeDataCsvContent) &&
        Objects.equals(this.mergeDataJsonContent, body6.mergeDataJsonContent) &&
        Objects.equals(this.mergeDataCsvUrl, body6.mergeDataCsvUrl) &&
        Objects.equals(this.mergeDataJsonUrl, body6.mergeDataJsonUrl) &&
        Objects.equals(this.password, body6.password);
  }

  @Override
  public int hashCode() {
    return Objects.hash(outputFormat, Objects.hashCode(fileContent), fileUrl, webhook, mergeTo, mergeData, Objects.hashCode(mergeDataCsvContent), Objects.hashCode(mergeDataJsonContent), mergeDataCsvUrl, mergeDataJsonUrl, password);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body6 {\n");
    
    sb.append("    outputFormat: ").append(toIndentedString(outputFormat)).append("\n");
    sb.append("    fileContent: ").append(toIndentedString(fileContent)).append("\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("    webhook: ").append(toIndentedString(webhook)).append("\n");
    sb.append("    mergeTo: ").append(toIndentedString(mergeTo)).append("\n");
    sb.append("    mergeData: ").append(toIndentedString(mergeData)).append("\n");
    sb.append("    mergeDataCsvContent: ").append(toIndentedString(mergeDataCsvContent)).append("\n");
    sb.append("    mergeDataJsonContent: ").append(toIndentedString(mergeDataJsonContent)).append("\n");
    sb.append("    mergeDataCsvUrl: ").append(toIndentedString(mergeDataCsvUrl)).append("\n");
    sb.append("    mergeDataJsonUrl: ").append(toIndentedString(mergeDataJsonUrl)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
