/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CompareDocumentResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class CompareDocumentResponse {
  @SerializedName("compare_url")
  private String compareUrl = null;

  @SerializedName("document_delete_url")
  private String documentDeleteUrl = null;

  public CompareDocumentResponse compareUrl(String compareUrl) {
    this.compareUrl = compareUrl;
    return this;
  }

   /**
   * Document session url to view document compare view
   * @return compareUrl
  **/
  @Schema(example = "https://writer.zoho.com/writer/officeapi/v1/document/compare/1650f22c990cbbce470e0418a808480021eeffebdad549f3e5226dc8cc83a7fc2e6e38a309785f4b8848a73aca2de5a53752f96243422c0a64aa7795ee7c8c103113db9ef722e86ec3d3b98ed71f1d61", description = "Document session url to view document compare view")
  public String getCompareUrl() {
    return compareUrl;
  }

  public void setCompareUrl(String compareUrl) {
    this.compareUrl = compareUrl;
  }

  public CompareDocumentResponse documentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
    return this;
  }

   /**
   * Url to delete document in zoho service.
   * @return documentDeleteUrl
  **/
  @Schema(example = "https://writer.zoho.com/writer/officeapi/v1/session/1650f22c990cbbce470e0418a808480021eeffebdad549f3e5226dc8cc83a7fc2e6e38a309785f4b8848a73aca2de5a53752f96243422c0a64aa7795ee7c8c103113db9ef722e86ec3d3b98ed71f1d61", description = "Url to delete document in zoho service.")
  public String getDocumentDeleteUrl() {
    return documentDeleteUrl;
  }

  public void setDocumentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompareDocumentResponse compareDocumentResponse = (CompareDocumentResponse) o;
    return Objects.equals(this.compareUrl, compareDocumentResponse.compareUrl) &&
        Objects.equals(this.documentDeleteUrl, compareDocumentResponse.documentDeleteUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compareUrl, documentDeleteUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompareDocumentResponse {\n");
    
    sb.append("    compareUrl: ").append(toIndentedString(compareUrl)).append("\n");
    sb.append("    documentDeleteUrl: ").append(toIndentedString(documentDeleteUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
