/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateSheetResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class CreateSheetResponse {
  @SerializedName("document_url")
  private String documentUrl = null;

  @SerializedName("document_id")
  private String documentId = null;

  @SerializedName("document_delete_url")
  private String documentDeleteUrl = null;

  public CreateSheetResponse documentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
    return this;
  }

   /**
   * Unique document session url to open the document
   * @return documentUrl
  **/
  @Schema(example = "https://sheet.zoho.com/sheet/editor.do?doc=d14bdc45d7b8c25d0e5d3061e5b4791cd5c0094b98621c7d279172ef78db5d7ce0e18ad2dfbda1de3ba07a32c40ec6e7d0b2d81a12065228e7a854ea7011ce92", description = "Unique document session url to open the document")
  public String getDocumentUrl() {
    return documentUrl;
  }

  public void setDocumentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
  }

  public CreateSheetResponse documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * Unique id to identify document in zoho service
   * @return documentId
  **/
  @Schema(example = "200001", description = "Unique id to identify document in zoho service")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public CreateSheetResponse documentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
    return this;
  }

   /**
   * Url to delete document in zoho service. When document deleted all other sessions associated with the document also be deleted automatically.
   * @return documentDeleteUrl
  **/
  @Schema(example = "https://sheet.zoho.com/sheet/officeapi/v1/spreadsheet/200001", description = "Url to delete document in zoho service. When document deleted all other sessions associated with the document also be deleted automatically.")
  public String getDocumentDeleteUrl() {
    return documentDeleteUrl;
  }

  public void setDocumentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateSheetResponse createSheetResponse = (CreateSheetResponse) o;
    return Objects.equals(this.documentUrl, createSheetResponse.documentUrl) &&
        Objects.equals(this.documentId, createSheetResponse.documentId) &&
        Objects.equals(this.documentDeleteUrl, createSheetResponse.documentDeleteUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentUrl, documentId, documentDeleteUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateSheetResponse {\n");
    
    sb.append("    documentUrl: ").append(toIndentedString(documentUrl)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    documentDeleteUrl: ").append(toIndentedString(documentDeleteUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
