/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateDocumentResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class CreateDocumentResponse {
  @SerializedName("document_url")
  private String documentUrl = null;

  @SerializedName("document_id")
  private String documentId = null;

  @SerializedName("save_url")
  private String saveUrl = null;

  @SerializedName("session_id")
  private String sessionId = null;

  @SerializedName("session_delete_url")
  private String sessionDeleteUrl = null;

  @SerializedName("document_delete_url")
  private String documentDeleteUrl = null;

  public CreateDocumentResponse documentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
    return this;
  }

   /**
   * Unique document session url to open the document
   * @return documentUrl
  **/
  @Schema(example = "https://writer.zoho.com/writer/officeapi/v1/document/d26aa7b8029bf4f8d34c7dd0013939234a6e15dac88646f02a69582375b8da130efffac249d0erouae4667dcbcfb7ac1d/open", description = "Unique document session url to open the document")
  public String getDocumentUrl() {
    return documentUrl;
  }

  public void setDocumentUrl(String documentUrl) {
    this.documentUrl = documentUrl;
  }

  public CreateDocumentResponse documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * Unique id to identify document in zoho service
   * @return documentId
  **/
  @Schema(example = "100001", description = "Unique id to identify document in zoho service")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public CreateDocumentResponse saveUrl(String saveUrl) {
    this.saveUrl = saveUrl;
    return this;
  }

   /**
   * Url to trigger save operation
   * @return saveUrl
  **/
  @Schema(example = "https://writer.zoho.com/writer/officeapi/v1/document/d26aa7b8029bf4f8d34c7dd0013939234a6e15dac88646f02a69582375b8da130efffac249d086aae4667dcbcfb7ac1d/save", description = "Url to trigger save operation")
  public String getSaveUrl() {
    return saveUrl;
  }

  public void setSaveUrl(String saveUrl) {
    this.saveUrl = saveUrl;
  }

  public CreateDocumentResponse sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Unique document sesstion id
   * @return sessionId
  **/
  @Schema(example = "axxrd26aa7b8029bf4f8d34c7dd0013939234a6e15dac88646f02a69582375b8da130efffac249d086aae4667dcbac9p", description = "Unique document sesstion id")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public CreateDocumentResponse sessionDeleteUrl(String sessionDeleteUrl) {
    this.sessionDeleteUrl = sessionDeleteUrl;
    return this;
  }

   /**
   * Url to delete document session in zoho service
   * @return sessionDeleteUrl
  **/
  @Schema(example = "https://writer.zoho.com/writer/officeapi/v1/session/d26aa7b8029bf4f8d34c7dd0013939234a6e15dac88646f02a69582375b8da130efffac249d086aae4667dcbcfb7ac1d", description = "Url to delete document session in zoho service")
  public String getSessionDeleteUrl() {
    return sessionDeleteUrl;
  }

  public void setSessionDeleteUrl(String sessionDeleteUrl) {
    this.sessionDeleteUrl = sessionDeleteUrl;
  }

  public CreateDocumentResponse documentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
    return this;
  }

   /**
   * Url to delete document in zoho service. When document deleted all other sessions associated with the document also be deleted automatically.
   * @return documentDeleteUrl
  **/
  @Schema(example = "https://writer.zoho.com/writer/officeapi/v1/document/100001", description = "Url to delete document in zoho service. When document deleted all other sessions associated with the document also be deleted automatically.")
  public String getDocumentDeleteUrl() {
    return documentDeleteUrl;
  }

  public void setDocumentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateDocumentResponse createDocumentResponse = (CreateDocumentResponse) o;
    return Objects.equals(this.documentUrl, createDocumentResponse.documentUrl) &&
        Objects.equals(this.documentId, createDocumentResponse.documentId) &&
        Objects.equals(this.saveUrl, createDocumentResponse.saveUrl) &&
        Objects.equals(this.sessionId, createDocumentResponse.sessionId) &&
        Objects.equals(this.sessionDeleteUrl, createDocumentResponse.sessionDeleteUrl) &&
        Objects.equals(this.documentDeleteUrl, createDocumentResponse.documentDeleteUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentUrl, documentId, saveUrl, sessionId, sessionDeleteUrl, documentDeleteUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateDocumentResponse {\n");
    
    sb.append("    documentUrl: ").append(toIndentedString(documentUrl)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    saveUrl: ").append(toIndentedString(saveUrl)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    sessionDeleteUrl: ").append(toIndentedString(sessionDeleteUrl)).append("\n");
    sb.append("    documentDeleteUrl: ").append(toIndentedString(documentDeleteUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
