/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * DocumentDefaults
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class DocumentDefaults {
  /**
   * To disable/enable track changes in the document
   */
  @JsonAdapter(TrackChangesEnum.Adapter.class)
  public enum TrackChangesEnum {
    ENABLED("enabled"),
    DISABLED("disabled");

    private String value;

    TrackChangesEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TrackChangesEnum fromValue(String text) {
      for (TrackChangesEnum b : TrackChangesEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TrackChangesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TrackChangesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TrackChangesEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TrackChangesEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("track_changes")
  private TrackChangesEnum trackChanges = TrackChangesEnum.DISABLED;

  public DocumentDefaults trackChanges(TrackChangesEnum trackChanges) {
    this.trackChanges = trackChanges;
    return this;
  }

   /**
   * To disable/enable track changes in the document
   * @return trackChanges
  **/
  @Schema(description = "To disable/enable track changes in the document")
  public TrackChangesEnum getTrackChanges() {
    return trackChanges;
  }

  public void setTrackChanges(TrackChangesEnum trackChanges) {
    this.trackChanges = trackChanges;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentDefaults documentDefaults = (DocumentDefaults) o;
    return Objects.equals(this.trackChanges, documentDefaults.trackChanges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trackChanges);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentDefaults {\n");
    
    sb.append("    trackChanges: ").append(toIndentedString(trackChanges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
