/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
/**
 * GetMergeFieldsReponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class GetMergeFieldsReponse {
  @SerializedName("merge")
  private List<Map<String, Object>> merge = null;

  public GetMergeFieldsReponse merge(List<Map<String, Object>> merge) {
    this.merge = merge;
    return this;
  }

  public GetMergeFieldsReponse addMergeItem(Map<String, Object> mergeItem) {
    if (this.merge == null) {
      this.merge = new ArrayList<Map<String, Object>>();
    }
    this.merge.add(mergeItem);
    return this;
  }

   /**
   * Array of information about merge fields persent in the document
   * @return merge
  **/
  @Schema(example = "[{\"id\":10,\"display_name\":\"Foo\"},{\"id\":20,\"display_name\":\"Bar\"}]", description = "Array of information about merge fields persent in the document")
  public List<Map<String, Object>> getMerge() {
    return merge;
  }

  public void setMerge(List<Map<String, Object>> merge) {
    this.merge = merge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMergeFieldsReponse getMergeFieldsReponse = (GetMergeFieldsReponse) o;
    return Objects.equals(this.merge, getMergeFieldsReponse.merge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMergeFieldsReponse {\n");
    
    sb.append("    merge: ").append(toIndentedString(merge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
