/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse2001
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class InlineResponse2001 {
  @SerializedName("doc_delete")
  private Boolean docDelete = null;

  public InlineResponse2001 docDelete(Boolean docDelete) {
    this.docDelete = docDelete;
    return this;
  }

   /**
   * Document delete request status
   * @return docDelete
  **/
  @Schema(description = "Document delete request status")
  public Boolean isDocDelete() {
    return docDelete;
  }

  public void setDocDelete(Boolean docDelete) {
    this.docDelete = docDelete;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.docDelete, inlineResponse2001.docDelete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(docDelete);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    docDelete: ").append(toIndentedString(docDelete)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
