/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MailMergeWebHookSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class MailMergeWebHookSettings {
  @SerializedName("invoke_url")
  private String invokeUrl = null;

  /**
   * when the merged documents needs to be posted in invoke_period.
   */
  @JsonAdapter(InvokePeriodEnum.Adapter.class)
  public enum InvokePeriodEnum {
    ONCOMPLETE("oncomplete"),
    ONEVERYRECORD("oneveryrecord");

    private String value;

    InvokePeriodEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static InvokePeriodEnum fromValue(String text) {
      for (InvokePeriodEnum b : InvokePeriodEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<InvokePeriodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final InvokePeriodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public InvokePeriodEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return InvokePeriodEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("invoke_period")
  private InvokePeriodEnum invokePeriod = null;

  public MailMergeWebHookSettings invokeUrl(String invokeUrl) {
    this.invokeUrl = invokeUrl;
    return this;
  }

   /**
   * Provide the webhook url in which the merged documents needs to be posted.
   * @return invokeUrl
  **/
  @Schema(description = "Provide the webhook url in which the merged documents needs to be posted.")
  public String getInvokeUrl() {
    return invokeUrl;
  }

  public void setInvokeUrl(String invokeUrl) {
    this.invokeUrl = invokeUrl;
  }

  public MailMergeWebHookSettings invokePeriod(InvokePeriodEnum invokePeriod) {
    this.invokePeriod = invokePeriod;
    return this;
  }

   /**
   * when the merged documents needs to be posted in invoke_period.
   * @return invokePeriod
  **/
  @Schema(description = "when the merged documents needs to be posted in invoke_period.")
  public InvokePeriodEnum getInvokePeriod() {
    return invokePeriod;
  }

  public void setInvokePeriod(InvokePeriodEnum invokePeriod) {
    this.invokePeriod = invokePeriod;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailMergeWebHookSettings mailMergeWebHookSettings = (MailMergeWebHookSettings) o;
    return Objects.equals(this.invokeUrl, mailMergeWebHookSettings.invokeUrl) &&
        Objects.equals(this.invokePeriod, mailMergeWebHookSettings.invokePeriod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invokeUrl, invokePeriod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailMergeWebHookSettings {\n");
    
    sb.append("    invokeUrl: ").append(toIndentedString(invokeUrl)).append("\n");
    sb.append("    invokePeriod: ").append(toIndentedString(invokePeriod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
