/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.MergeAndDeliverRecord;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * MergeAndDeliverReponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class MergeAndDeliverReponse {
  @SerializedName("merge_report_data_url")
  private String mergeReportDataUrl = null;

  @SerializedName("records")
  private List<MergeAndDeliverRecord> records = null;

  public MergeAndDeliverReponse mergeReportDataUrl(String mergeReportDataUrl) {
    this.mergeReportDataUrl = mergeReportDataUrl;
    return this;
  }

   /**
   * helps to get or retrieve the status of the report by passing the {apikey} in &#x27;GET&#x27; method.
   * @return mergeReportDataUrl
  **/
  @Schema(description = "helps to get or retrieve the status of the report by passing the {apikey} in 'GET' method.")
  public String getMergeReportDataUrl() {
    return mergeReportDataUrl;
  }

  public void setMergeReportDataUrl(String mergeReportDataUrl) {
    this.mergeReportDataUrl = mergeReportDataUrl;
  }

  public MergeAndDeliverReponse records(List<MergeAndDeliverRecord> records) {
    this.records = records;
    return this;
  }

  public MergeAndDeliverReponse addRecordsItem(MergeAndDeliverRecord recordsItem) {
    if (this.records == null) {
      this.records = new ArrayList<MergeAndDeliverRecord>();
    }
    this.records.add(recordsItem);
    return this;
  }

   /**
   * Array of information about merge fields persent in the document
   * @return records
  **/
  @Schema(description = "Array of information about merge fields persent in the document")
  public List<MergeAndDeliverRecord> getRecords() {
    return records;
  }

  public void setRecords(List<MergeAndDeliverRecord> records) {
    this.records = records;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergeAndDeliverReponse mergeAndDeliverReponse = (MergeAndDeliverReponse) o;
    return Objects.equals(this.mergeReportDataUrl, mergeAndDeliverReponse.mergeReportDataUrl) &&
        Objects.equals(this.records, mergeAndDeliverReponse.records);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mergeReportDataUrl, records);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergeAndDeliverReponse {\n");
    
    sb.append("    mergeReportDataUrl: ").append(toIndentedString(mergeReportDataUrl)).append("\n");
    sb.append("    records: ").append(toIndentedString(records)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
