/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.WriterSupportedFormats;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OutputOptions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class OutputOptions {
  @SerializedName("format")
  private WriterSupportedFormats format = null;

  @SerializedName("document_name")
  private String documentName = null;

  @SerializedName("password")
  private String password = null;

  /**
   * Specify how the track changed content needs to be reflected in converted file.
   */
  @JsonAdapter(IncludeChangesEnum.Adapter.class)
  public enum IncludeChangesEnum {
    AS_MARKUPS("as_markups"),
    ALL("all"),
    NONE("none");

    private String value;

    IncludeChangesEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static IncludeChangesEnum fromValue(String text) {
      for (IncludeChangesEnum b : IncludeChangesEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<IncludeChangesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IncludeChangesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IncludeChangesEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return IncludeChangesEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("include_changes")
  private IncludeChangesEnum includeChanges = null;

  /**
   * Specify if the comments needs to be included in the converted file or not.
   */
  @JsonAdapter(IncludeCommentsEnum.Adapter.class)
  public enum IncludeCommentsEnum {
    ALL("all"),
    NONE("none");

    private String value;

    IncludeCommentsEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static IncludeCommentsEnum fromValue(String text) {
      for (IncludeCommentsEnum b : IncludeCommentsEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<IncludeCommentsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IncludeCommentsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IncludeCommentsEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return IncludeCommentsEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("include_comments")
  private IncludeCommentsEnum includeComments = null;

  public OutputOptions format(WriterSupportedFormats format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @Schema(required = true, description = "")
  public WriterSupportedFormats getFormat() {
    return format;
  }

  public void setFormat(WriterSupportedFormats format) {
    this.format = format;
  }

  public OutputOptions documentName(String documentName) {
    this.documentName = documentName;
    return this;
  }

   /**
   * Specify the name for the converted document.
   * @return documentName
  **/
  @Schema(required = true, description = "Specify the name for the converted document.")
  public String getDocumentName() {
    return documentName;
  }

  public void setDocumentName(String documentName) {
    this.documentName = documentName;
  }

  public OutputOptions password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Specify a password if you would like to protect the converted document.
   * @return password
  **/
  @Schema(description = "Specify a password if you would like to protect the converted document.")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public OutputOptions includeChanges(IncludeChangesEnum includeChanges) {
    this.includeChanges = includeChanges;
    return this;
  }

   /**
   * Specify how the track changed content needs to be reflected in converted file.
   * @return includeChanges
  **/
  @Schema(description = "Specify how the track changed content needs to be reflected in converted file.")
  public IncludeChangesEnum getIncludeChanges() {
    return includeChanges;
  }

  public void setIncludeChanges(IncludeChangesEnum includeChanges) {
    this.includeChanges = includeChanges;
  }

  public OutputOptions includeComments(IncludeCommentsEnum includeComments) {
    this.includeComments = includeComments;
    return this;
  }

   /**
   * Specify if the comments needs to be included in the converted file or not.
   * @return includeComments
  **/
  @Schema(description = "Specify if the comments needs to be included in the converted file or not.")
  public IncludeCommentsEnum getIncludeComments() {
    return includeComments;
  }

  public void setIncludeComments(IncludeCommentsEnum includeComments) {
    this.includeComments = includeComments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputOptions outputOptions = (OutputOptions) o;
    return Objects.equals(this.format, outputOptions.format) &&
        Objects.equals(this.documentName, outputOptions.documentName) &&
        Objects.equals(this.password, outputOptions.password) &&
        Objects.equals(this.includeChanges, outputOptions.includeChanges) &&
        Objects.equals(this.includeComments, outputOptions.includeComments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(format, documentName, password, includeChanges, includeComments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputOptions {\n");
    
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    documentName: ").append(toIndentedString(documentName)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    includeChanges: ").append(toIndentedString(includeChanges)).append("\n");
    sb.append("    includeComments: ").append(toIndentedString(includeComments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
