/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * PlanDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class PlanDetails {
  @SerializedName("apikey_id")
  private BigDecimal apikeyId = null;

  @SerializedName("plan_name")
  private String planName = null;

  @SerializedName("payment_link")
  private String paymentLink = null;

  /**
   * Subscription billing cycle type. i.e - Yearly or Monthly
   */
  @JsonAdapter(SubscriptionIntervalEnum.Adapter.class)
  public enum SubscriptionIntervalEnum {
    YEARLY("yearly"),
    MONTHLY("monthly");

    private String value;

    SubscriptionIntervalEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static SubscriptionIntervalEnum fromValue(String text) {
      for (SubscriptionIntervalEnum b : SubscriptionIntervalEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<SubscriptionIntervalEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SubscriptionIntervalEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SubscriptionIntervalEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SubscriptionIntervalEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("subscription_interval")
  private SubscriptionIntervalEnum subscriptionInterval = null;

  @SerializedName("subscription_period")
  private String subscriptionPeriod = null;

  @SerializedName("usage_limit")
  private Integer usageLimit = null;

  @SerializedName("apikey_generated_time")
  private String apikeyGeneratedTime = null;

  @SerializedName("total_usage")
  private Integer totalUsage = null;

  @SerializedName("remaining_usage_limit")
  private Integer remainingUsageLimit = null;

  @SerializedName("last_payment_date_ms")
  private BigDecimal lastPaymentDateMs = null;

  @SerializedName("next_payment_date_ms")
  private BigDecimal nextPaymentDateMs = null;

  @SerializedName("last_payment_date")
  private String lastPaymentDate = null;

  @SerializedName("next_payment_date")
  private String nextPaymentDate = null;

  public PlanDetails apikeyId(BigDecimal apikeyId) {
    this.apikeyId = apikeyId;
    return this;
  }

   /**
   * Unix id associted with apikey profile
   * @return apikeyId
  **/
  @Schema(example = "1001000000490041", description = "Unix id associted with apikey profile")
  public BigDecimal getApikeyId() {
    return apikeyId;
  }

  public void setApikeyId(BigDecimal apikeyId) {
    this.apikeyId = apikeyId;
  }

  public PlanDetails planName(String planName) {
    this.planName = planName;
    return this;
  }

   /**
   * Current plan name
   * @return planName
  **/
  @Schema(example = "Commercial", description = "Current plan name")
  public String getPlanName() {
    return planName;
  }

  public void setPlanName(String planName) {
    this.planName = planName;
  }

  public PlanDetails paymentLink(String paymentLink) {
    this.paymentLink = paymentLink;
    return this;
  }

   /**
   * Link to make payment
   * @return paymentLink
  **/
  @Schema(example = "https://payments.zoho.com/html/store/index.html#subscription?serviceId=2401&customId=0bf26a45b467c49cbf12726ebfb01235", description = "Link to make payment")
  public String getPaymentLink() {
    return paymentLink;
  }

  public void setPaymentLink(String paymentLink) {
    this.paymentLink = paymentLink;
  }

  public PlanDetails subscriptionInterval(SubscriptionIntervalEnum subscriptionInterval) {
    this.subscriptionInterval = subscriptionInterval;
    return this;
  }

   /**
   * Subscription billing cycle type. i.e - Yearly or Monthly
   * @return subscriptionInterval
  **/
  @Schema(description = "Subscription billing cycle type. i.e - Yearly or Monthly")
  public SubscriptionIntervalEnum getSubscriptionInterval() {
    return subscriptionInterval;
  }

  public void setSubscriptionInterval(SubscriptionIntervalEnum subscriptionInterval) {
    this.subscriptionInterval = subscriptionInterval;
  }

  public PlanDetails subscriptionPeriod(String subscriptionPeriod) {
    this.subscriptionPeriod = subscriptionPeriod;
    return this;
  }

   /**
   * Subscription period string
   * @return subscriptionPeriod
  **/
  @Schema(example = "2019-08-06 - 2020-08-06", description = "Subscription period string")
  public String getSubscriptionPeriod() {
    return subscriptionPeriod;
  }

  public void setSubscriptionPeriod(String subscriptionPeriod) {
    this.subscriptionPeriod = subscriptionPeriod;
  }

  public PlanDetails usageLimit(Integer usageLimit) {
    this.usageLimit = usageLimit;
    return this;
  }

   /**
   * Allowed api limit for current plan
   * @return usageLimit
  **/
  @Schema(example = "5000", description = "Allowed api limit for current plan")
  public Integer getUsageLimit() {
    return usageLimit;
  }

  public void setUsageLimit(Integer usageLimit) {
    this.usageLimit = usageLimit;
  }

  public PlanDetails apikeyGeneratedTime(String apikeyGeneratedTime) {
    this.apikeyGeneratedTime = apikeyGeneratedTime;
    return this;
  }

   /**
   * Time when the apikey profile created
   * @return apikeyGeneratedTime
  **/
  @Schema(example = "2017-02-07T05:26:45Z", description = "Time when the apikey profile created")
  public String getApikeyGeneratedTime() {
    return apikeyGeneratedTime;
  }

  public void setApikeyGeneratedTime(String apikeyGeneratedTime) {
    this.apikeyGeneratedTime = apikeyGeneratedTime;
  }

  public PlanDetails totalUsage(Integer totalUsage) {
    this.totalUsage = totalUsage;
    return this;
  }

   /**
   * Total api usage count in this billing cycle
   * @return totalUsage
  **/
  @Schema(example = "500", description = "Total api usage count in this billing cycle")
  public Integer getTotalUsage() {
    return totalUsage;
  }

  public void setTotalUsage(Integer totalUsage) {
    this.totalUsage = totalUsage;
  }

  public PlanDetails remainingUsageLimit(Integer remainingUsageLimit) {
    this.remainingUsageLimit = remainingUsageLimit;
    return this;
  }

   /**
   * Remained allowed api limit
   * @return remainingUsageLimit
  **/
  @Schema(example = "4500", description = "Remained allowed api limit")
  public Integer getRemainingUsageLimit() {
    return remainingUsageLimit;
  }

  public void setRemainingUsageLimit(Integer remainingUsageLimit) {
    this.remainingUsageLimit = remainingUsageLimit;
  }

  public PlanDetails lastPaymentDateMs(BigDecimal lastPaymentDateMs) {
    this.lastPaymentDateMs = lastPaymentDateMs;
    return this;
  }

   /**
   * Unix of last subscription payment date for Office Integrator service
   * @return lastPaymentDateMs
  **/
  @Schema(example = "1565074960213", description = "Unix of last subscription payment date for Office Integrator service")
  public BigDecimal getLastPaymentDateMs() {
    return lastPaymentDateMs;
  }

  public void setLastPaymentDateMs(BigDecimal lastPaymentDateMs) {
    this.lastPaymentDateMs = lastPaymentDateMs;
  }

  public PlanDetails nextPaymentDateMs(BigDecimal nextPaymentDateMs) {
    this.nextPaymentDateMs = nextPaymentDateMs;
    return this;
  }

   /**
   * Unix of next subscription payment date for Office Integrator service
   * @return nextPaymentDateMs
  **/
  @Schema(example = "1565074960213", description = "Unix of next subscription payment date for Office Integrator service")
  public BigDecimal getNextPaymentDateMs() {
    return nextPaymentDateMs;
  }

  public void setNextPaymentDateMs(BigDecimal nextPaymentDateMs) {
    this.nextPaymentDateMs = nextPaymentDateMs;
  }

  public PlanDetails lastPaymentDate(String lastPaymentDate) {
    this.lastPaymentDate = lastPaymentDate;
    return this;
  }

   /**
   * Next payment date string value
   * @return lastPaymentDate
  **/
  @Schema(example = "2020-07-06T07:02:40Z", description = "Next payment date string value")
  public String getLastPaymentDate() {
    return lastPaymentDate;
  }

  public void setLastPaymentDate(String lastPaymentDate) {
    this.lastPaymentDate = lastPaymentDate;
  }

  public PlanDetails nextPaymentDate(String nextPaymentDate) {
    this.nextPaymentDate = nextPaymentDate;
    return this;
  }

   /**
   * Next payment date string value
   * @return nextPaymentDate
  **/
  @Schema(example = "2020-07-06T07:02:40Z", description = "Next payment date string value")
  public String getNextPaymentDate() {
    return nextPaymentDate;
  }

  public void setNextPaymentDate(String nextPaymentDate) {
    this.nextPaymentDate = nextPaymentDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlanDetails planDetails = (PlanDetails) o;
    return Objects.equals(this.apikeyId, planDetails.apikeyId) &&
        Objects.equals(this.planName, planDetails.planName) &&
        Objects.equals(this.paymentLink, planDetails.paymentLink) &&
        Objects.equals(this.subscriptionInterval, planDetails.subscriptionInterval) &&
        Objects.equals(this.subscriptionPeriod, planDetails.subscriptionPeriod) &&
        Objects.equals(this.usageLimit, planDetails.usageLimit) &&
        Objects.equals(this.apikeyGeneratedTime, planDetails.apikeyGeneratedTime) &&
        Objects.equals(this.totalUsage, planDetails.totalUsage) &&
        Objects.equals(this.remainingUsageLimit, planDetails.remainingUsageLimit) &&
        Objects.equals(this.lastPaymentDateMs, planDetails.lastPaymentDateMs) &&
        Objects.equals(this.nextPaymentDateMs, planDetails.nextPaymentDateMs) &&
        Objects.equals(this.lastPaymentDate, planDetails.lastPaymentDate) &&
        Objects.equals(this.nextPaymentDate, planDetails.nextPaymentDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apikeyId, planName, paymentLink, subscriptionInterval, subscriptionPeriod, usageLimit, apikeyGeneratedTime, totalUsage, remainingUsageLimit, lastPaymentDateMs, nextPaymentDateMs, lastPaymentDate, nextPaymentDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlanDetails {\n");
    
    sb.append("    apikeyId: ").append(toIndentedString(apikeyId)).append("\n");
    sb.append("    planName: ").append(toIndentedString(planName)).append("\n");
    sb.append("    paymentLink: ").append(toIndentedString(paymentLink)).append("\n");
    sb.append("    subscriptionInterval: ").append(toIndentedString(subscriptionInterval)).append("\n");
    sb.append("    subscriptionPeriod: ").append(toIndentedString(subscriptionPeriod)).append("\n");
    sb.append("    usageLimit: ").append(toIndentedString(usageLimit)).append("\n");
    sb.append("    apikeyGeneratedTime: ").append(toIndentedString(apikeyGeneratedTime)).append("\n");
    sb.append("    totalUsage: ").append(toIndentedString(totalUsage)).append("\n");
    sb.append("    remainingUsageLimit: ").append(toIndentedString(remainingUsageLimit)).append("\n");
    sb.append("    lastPaymentDateMs: ").append(toIndentedString(lastPaymentDateMs)).append("\n");
    sb.append("    nextPaymentDateMs: ").append(toIndentedString(nextPaymentDateMs)).append("\n");
    sb.append("    lastPaymentDate: ").append(toIndentedString(lastPaymentDate)).append("\n");
    sb.append("    nextPaymentDate: ").append(toIndentedString(nextPaymentDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
