/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PreviewResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class PreviewResponse {
  @SerializedName("preview_url")
  private String previewUrl = null;

  @SerializedName("document_id")
  private String documentId = null;

  @SerializedName("session_id")
  private String sessionId = null;

  @SerializedName("session_delete_url")
  private String sessionDeleteUrl = null;

  @SerializedName("document_delete_url")
  private String documentDeleteUrl = null;

  public PreviewResponse previewUrl(String previewUrl) {
    this.previewUrl = previewUrl;
    return this;
  }

   /**
   * Unique document preview session url to view the document
   * @return previewUrl
  **/
  @Schema(example = "https://writer.zoho.com/writer/officeapi/v1/document/preview/d26aa7b8029bf4f8d34c7dd0013939237c7426dd7b014b7c5cd9fa07cdd21f0e304693ffbf26ba091b4f8d5350ec9bb8/open", description = "Unique document preview session url to view the document")
  public String getPreviewUrl() {
    return previewUrl;
  }

  public void setPreviewUrl(String previewUrl) {
    this.previewUrl = previewUrl;
  }

  public PreviewResponse documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * Unique id to identify document in zoho service
   * @return documentId
  **/
  @Schema(example = "100002", description = "Unique id to identify document in zoho service")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public PreviewResponse sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Unique document sesstion id
   * @return sessionId
  **/
  @Schema(example = "d26aa7b8029bf4f8d34c7dd0013939237c7426dd7b014b7c5cd9fa07cdd21f0e304693ffbf26ba091b4f8d5350ec9bb8", description = "Unique document sesstion id")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public PreviewResponse sessionDeleteUrl(String sessionDeleteUrl) {
    this.sessionDeleteUrl = sessionDeleteUrl;
    return this;
  }

   /**
   * Url to delete document session in zoho service
   * @return sessionDeleteUrl
  **/
  @Schema(example = "https://writer.zoho.com/writer/officeapi/v1/session/d26aa7b8029bf4f8d34c7dd0013939237c7426dd7b014b7c5cd9fa07cdd21f0e304693ffbf26ba091b4f8d5350ec9bb8", description = "Url to delete document session in zoho service")
  public String getSessionDeleteUrl() {
    return sessionDeleteUrl;
  }

  public void setSessionDeleteUrl(String sessionDeleteUrl) {
    this.sessionDeleteUrl = sessionDeleteUrl;
  }

  public PreviewResponse documentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
    return this;
  }

   /**
   * Url to delete document in zoho service. When document deleted all other sessions associated with the document also be deleted automatically.
   * @return documentDeleteUrl
  **/
  @Schema(example = "https://writer.zoho.com/writer/officeapi/v1/document/100002", description = "Url to delete document in zoho service. When document deleted all other sessions associated with the document also be deleted automatically.")
  public String getDocumentDeleteUrl() {
    return documentDeleteUrl;
  }

  public void setDocumentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreviewResponse previewResponse = (PreviewResponse) o;
    return Objects.equals(this.previewUrl, previewResponse.previewUrl) &&
        Objects.equals(this.documentId, previewResponse.documentId) &&
        Objects.equals(this.sessionId, previewResponse.sessionId) &&
        Objects.equals(this.sessionDeleteUrl, previewResponse.sessionDeleteUrl) &&
        Objects.equals(this.documentDeleteUrl, previewResponse.documentDeleteUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(previewUrl, documentId, sessionId, sessionDeleteUrl, documentDeleteUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreviewResponse {\n");
    
    sb.append("    previewUrl: ").append(toIndentedString(previewUrl)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    sessionDeleteUrl: ").append(toIndentedString(sessionDeleteUrl)).append("\n");
    sb.append("    documentDeleteUrl: ").append(toIndentedString(documentDeleteUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
