/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * PreviewSheetResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class PreviewSheetResponse {
  @SerializedName("preview_url")
  private String previewUrl = null;

  @SerializedName("document_id")
  private String documentId = null;

  @SerializedName("document_delete_url")
  private String documentDeleteUrl = null;

  public PreviewSheetResponse previewUrl(String previewUrl) {
    this.previewUrl = previewUrl;
    return this;
  }

   /**
   * Preview sheet document session url
   * @return previewUrl
  **/
  @Schema(example = "https://sheet.zoho.com/sheet/editor.do?doc=0b6d2f1227e9ebb017e6cf5cceeb5a032044c949eb4e507eaa3b0f296e4122ef916893e55b2fc34c4119edb825c3a965ee971551d08d111421a02c47b49a1915", description = "Preview sheet document session url")
  public String getPreviewUrl() {
    return previewUrl;
  }

  public void setPreviewUrl(String previewUrl) {
    this.previewUrl = previewUrl;
  }

  public PreviewSheetResponse documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * Unique id to identify document in zoho service
   * @return documentId
  **/
  @Schema(example = "200002", description = "Unique id to identify document in zoho service")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public PreviewSheetResponse documentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
    return this;
  }

   /**
   * Url to delete sheet document in zoho service. When document deleted all other sessions associated with the document also be deleted automatically.
   * @return documentDeleteUrl
  **/
  @Schema(example = "https://sheet.zoho.com/sheet/officeapi/v1/spreadsheet/200002", description = "Url to delete sheet document in zoho service. When document deleted all other sessions associated with the document also be deleted automatically.")
  public String getDocumentDeleteUrl() {
    return documentDeleteUrl;
  }

  public void setDocumentDeleteUrl(String documentDeleteUrl) {
    this.documentDeleteUrl = documentDeleteUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreviewSheetResponse previewSheetResponse = (PreviewSheetResponse) o;
    return Objects.equals(this.previewUrl, previewSheetResponse.previewUrl) &&
        Objects.equals(this.documentId, previewSheetResponse.documentId) &&
        Objects.equals(this.documentDeleteUrl, previewSheetResponse.documentDeleteUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(previewUrl, documentId, documentDeleteUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreviewSheetResponse {\n");
    
    sb.append("    previewUrl: ").append(toIndentedString(previewUrl)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    documentDeleteUrl: ").append(toIndentedString(documentDeleteUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
