/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.ShowSupportedLanguages;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SheetEditorSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class SheetEditorSettings {
  /**
   * Country code based on which the sheet editor interface will open.
   */
  @JsonAdapter(CountryEnum.Adapter.class)
  public enum CountryEnum {
    IN("IN"),
    US("US"),
    GB("GB"),
    MX("MX"),
    BR("BR");

    private String value;

    CountryEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static CountryEnum fromValue(String text) {
      for (CountryEnum b : CountryEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<CountryEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CountryEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CountryEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CountryEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("country")
  private CountryEnum country = null;

  @SerializedName("language")
  private ShowSupportedLanguages language = null;

  public SheetEditorSettings country(CountryEnum country) {
    this.country = country;
    return this;
  }

   /**
   * Country code based on which the sheet editor interface will open.
   * @return country
  **/
  @Schema(description = "Country code based on which the sheet editor interface will open.")
  public CountryEnum getCountry() {
    return country;
  }

  public void setCountry(CountryEnum country) {
    this.country = country;
  }

  public SheetEditorSettings language(ShowSupportedLanguages language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(description = "")
  public ShowSupportedLanguages getLanguage() {
    return language;
  }

  public void setLanguage(ShowSupportedLanguages language) {
    this.language = language;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SheetEditorSettings sheetEditorSettings = (SheetEditorSettings) o;
    return Objects.equals(this.country, sheetEditorSettings.country) &&
        Objects.equals(this.language, sheetEditorSettings.language);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, language);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SheetEditorSettings {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
