/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.SheetSupportedFormats;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SheetCallbackSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class SheetCallbackSettings {
  @SerializedName("save_url")
  private String saveUrl = "";

  @SerializedName("save_format")
  private SheetSupportedFormats saveFormat = null;

  @SerializedName("context_info")
  private String contextInfo = "";

  public SheetCallbackSettings saveUrl(String saveUrl) {
    this.saveUrl = saveUrl;
    return this;
  }

   /**
   * Provide your server location to which the latest content needs to be pushed back when the &#x27;Save&#x27; is performed.
   * @return saveUrl
  **/
  @Schema(description = "Provide your server location to which the latest content needs to be pushed back when the 'Save' is performed.")
  public String getSaveUrl() {
    return saveUrl;
  }

  public void setSaveUrl(String saveUrl) {
    this.saveUrl = saveUrl;
  }

  public SheetCallbackSettings saveFormat(SheetSupportedFormats saveFormat) {
    this.saveFormat = saveFormat;
    return this;
  }

   /**
   * Get saveFormat
   * @return saveFormat
  **/
  @Schema(required = true, description = "")
  public SheetSupportedFormats getSaveFormat() {
    return saveFormat;
  }

  public void setSaveFormat(SheetSupportedFormats saveFormat) {
    this.saveFormat = saveFormat;
  }

  public SheetCallbackSettings contextInfo(String contextInfo) {
    this.contextInfo = contextInfo;
    return this;
  }

   /**
   * additional doc or user info
   * @return contextInfo
  **/
  @Schema(description = "additional doc or user info")
  public String getContextInfo() {
    return contextInfo;
  }

  public void setContextInfo(String contextInfo) {
    this.contextInfo = contextInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SheetCallbackSettings sheetCallbackSettings = (SheetCallbackSettings) o;
    return Objects.equals(this.saveUrl, sheetCallbackSettings.saveUrl) &&
        Objects.equals(this.saveFormat, sheetCallbackSettings.saveFormat) &&
        Objects.equals(this.contextInfo, sheetCallbackSettings.contextInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saveUrl, saveFormat, contextInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SheetCallbackSettings {\n");
    
    sb.append("    saveUrl: ").append(toIndentedString(saveUrl)).append("\n");
    sb.append("    saveFormat: ").append(toIndentedString(saveFormat)).append("\n");
    sb.append("    contextInfo: ").append(toIndentedString(contextInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
