/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Spreadsheet formats supported by Zoho Sheet:   * &#x60;xls&#x60; - Microsoft Excel Spreadsheet   * &#x60;xlsx&#x60; - Microsoft Excel Spreadsheet 2010+   * &#x60;ods&#x60; - OpenOffice Open Document Spreadsheet   * &#x60;csv&#x60; - Comma Separated Values   * &#x60;tsv&#x60; - Tab Separated Values 
 */
@JsonAdapter(SheetSupportedFormats.Adapter.class)
public enum SheetSupportedFormats {
  XLS("xls"),
  XLSX("xlsx"),
  ODS("ods"),
  CSV("csv"),
  TSV("tsv");

  private String value;

  SheetSupportedFormats(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SheetSupportedFormats fromValue(String text) {
    for (SheetSupportedFormats b : SheetSupportedFormats.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SheetSupportedFormats> {
    @Override
    public void write(final JsonWriter jsonWriter, final SheetSupportedFormats enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SheetSupportedFormats read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SheetSupportedFormats.fromValue(String.valueOf(value));
    }
  }
}
