/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SheetReadOnlyPermissions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class SheetReadOnlyPermissions {
  @SerializedName("document.export")
  private Boolean documentExport = null;

  @SerializedName("document.print")
  private Boolean documentPrint = null;

  public SheetReadOnlyPermissions documentExport(Boolean documentExport) {
    this.documentExport = documentExport;
    return this;
  }

   /**
   * To enable or disable download option
   * @return documentExport
  **/
  @Schema(description = "To enable or disable download option")
  public Boolean isDocumentExport() {
    return documentExport;
  }

  public void setDocumentExport(Boolean documentExport) {
    this.documentExport = documentExport;
  }

  public SheetReadOnlyPermissions documentPrint(Boolean documentPrint) {
    this.documentPrint = documentPrint;
    return this;
  }

   /**
   * To enable or disable print option
   * @return documentPrint
  **/
  @Schema(description = "To enable or disable print option")
  public Boolean isDocumentPrint() {
    return documentPrint;
  }

  public void setDocumentPrint(Boolean documentPrint) {
    this.documentPrint = documentPrint;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SheetReadOnlyPermissions sheetReadOnlyPermissions = (SheetReadOnlyPermissions) o;
    return Objects.equals(this.documentExport, sheetReadOnlyPermissions.documentExport) &&
        Objects.equals(this.documentPrint, sheetReadOnlyPermissions.documentPrint);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentExport, documentPrint);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SheetReadOnlyPermissions {\n");
    
    sb.append("    documentExport: ").append(toIndentedString(documentExport)).append("\n");
    sb.append("    documentPrint: ").append(toIndentedString(documentPrint)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
