/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Languages supported by Zoho Writer:   * &#x60;en&#x60; - English   * &#x60;da&#x60; - Danish   * &#x60;de&#x60; - German   * &#x60;es&#x60; - Spanish   * &#x60;fr&#x60; - French   * &#x60;it&#x60; - Italian   * &#x60;ja&#x60; - Japanese   * &#x60;nl&#x60; - Dutch   * &#x60;pl&#x60; - Polish   * &#x60;sv&#x60; - Swedish   * &#x60;tr&#x60; - Turkish   * &#x60;zh&#x60; - Chinese   * &#x60;zh_CN&#x60; - Chinese/China   &gt; externalDocs:     description: Find list of support language list     url: https://www.zoho.com/officeplatform/integrator/help/supported-languages.html 
 */
@JsonAdapter(ShowSupportedLanguages.Adapter.class)
public enum ShowSupportedLanguages {
  EN("en"),
  DA("da"),
  DE("de"),
  ES("es"),
  FR("fr"),
  IT("it"),
  JA("ja"),
  NL("nl"),
  PL("pl"),
  SV("sv"),
  TR("tr"),
  ZH("zh"),
  ZH_CN("zh_CN");

  private String value;

  ShowSupportedLanguages(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ShowSupportedLanguages fromValue(String text) {
    for (ShowSupportedLanguages b : ShowSupportedLanguages.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ShowSupportedLanguages> {
    @Override
    public void write(final JsonWriter jsonWriter, final ShowSupportedLanguages enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ShowSupportedLanguages read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ShowSupportedLanguages.fromValue(String.valueOf(value));
    }
  }
}
