/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Presentation formats supported by Zoho Show:   * &#x60;ppt&#x60; - Microsoft PowerPoint   * &#x60;pptx&#x60; - Microsoft PowerPoint 2010+   * &#x60;pps&#x60; - PowerPoint Slideshow   * &#x60;ppsx&#x60; - PowerPoint Slideshow 2010+   * &#x60;odp&#x60; - OpenOffice Open Document Presentation   * &#x60;sxi&#x60; - OpenOffice.org Presentation File    
 */
@JsonAdapter(ShowSupportedFormats.Adapter.class)
public enum ShowSupportedFormats {
  PPT("ppt"),
  PPTX("pptx"),
  PPS("pps"),
  PPSX("ppsx"),
  ODP("odp"),
  SXI("sxi");

  private String value;

  ShowSupportedFormats(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ShowSupportedFormats fromValue(String text) {
    for (ShowSupportedFormats b : ShowSupportedFormats.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ShowSupportedFormats> {
    @Override
    public void write(final JsonWriter jsonWriter, final ShowSupportedFormats enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ShowSupportedFormats read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ShowSupportedFormats.fromValue(String.valueOf(value));
    }
  }
}
