/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UIOptions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class UIOptions {
  /**
   * Show/hide save button inside the zoho editor
   */
  @JsonAdapter(SaveButtonEnum.Adapter.class)
  public enum SaveButtonEnum {
    SHOW("show"),
    HIDE("hide");

    private String value;

    SaveButtonEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static SaveButtonEnum fromValue(String text) {
      for (SaveButtonEnum b : SaveButtonEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<SaveButtonEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SaveButtonEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SaveButtonEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SaveButtonEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("save_button")
  private SaveButtonEnum saveButton = SaveButtonEnum.SHOW;

  /**
   * Show/hide chat option inside the zoho editor
   */
  @JsonAdapter(ChatPanelEnum.Adapter.class)
  public enum ChatPanelEnum {
    SHOW("show"),
    HIDE("hide");

    private String value;

    ChatPanelEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ChatPanelEnum fromValue(String text) {
      for (ChatPanelEnum b : ChatPanelEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ChatPanelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ChatPanelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ChatPanelEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ChatPanelEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("chat_panel")
  private ChatPanelEnum chatPanel = ChatPanelEnum.SHOW;

  public UIOptions saveButton(SaveButtonEnum saveButton) {
    this.saveButton = saveButton;
    return this;
  }

   /**
   * Show/hide save button inside the zoho editor
   * @return saveButton
  **/
  @Schema(description = "Show/hide save button inside the zoho editor")
  public SaveButtonEnum getSaveButton() {
    return saveButton;
  }

  public void setSaveButton(SaveButtonEnum saveButton) {
    this.saveButton = saveButton;
  }

  public UIOptions chatPanel(ChatPanelEnum chatPanel) {
    this.chatPanel = chatPanel;
    return this;
  }

   /**
   * Show/hide chat option inside the zoho editor
   * @return chatPanel
  **/
  @Schema(description = "Show/hide chat option inside the zoho editor")
  public ChatPanelEnum getChatPanel() {
    return chatPanel;
  }

  public void setChatPanel(ChatPanelEnum chatPanel) {
    this.chatPanel = chatPanel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UIOptions uiOptions = (UIOptions) o;
    return Objects.equals(this.saveButton, uiOptions.saveButton) &&
        Objects.equals(this.chatPanel, uiOptions.chatPanel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saveButton, chatPanel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UIOptions {\n");
    
    sb.append("    saveButton: ").append(toIndentedString(saveButton)).append("\n");
    sb.append("    chatPanel: ").append(toIndentedString(chatPanel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
