/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WatermarkSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class WatermarkSettings {
  @SerializedName("text")
  private String text = null;

  /**
   * Provide of watermark to be applied inside the &#x27;type&#x27; key. For now only type &#x27;text&#x27; only supported
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    TEXT("text");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("type")
  private TypeEnum type = TypeEnum.TEXT;

  /**
   * Orientation of watermark to be applied on the document
   */
  @JsonAdapter(OrientationEnum.Adapter.class)
  public enum OrientationEnum {
    DIAGONAL("diagonal"),
    HORIZONTAL("horizontal"),
    VERTICAL("vertical");

    private String value;

    OrientationEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static OrientationEnum fromValue(String text) {
      for (OrientationEnum b : OrientationEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<OrientationEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OrientationEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OrientationEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return OrientationEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("orientation")
  private OrientationEnum orientation = OrientationEnum.DIAGONAL;

  @SerializedName("font_name")
  private String fontName = "Arial";

  @SerializedName("font_size")
  private Integer fontSize = 16;

  @SerializedName("font_color")
  private String fontColor = "#000000";

  @SerializedName("opacity")
  private Integer opacity = 0;

  public WatermarkSettings text(String text) {
    this.text = text;
    return this;
  }

   /**
   * Specify the watermark content inside the &#x27;text&#x27; key
   * @return text
  **/
  @Schema(example = "Zoho Corporation Private Limited", required = true, description = "Specify the watermark content inside the 'text' key")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public WatermarkSettings type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Provide of watermark to be applied inside the &#x27;type&#x27; key. For now only type &#x27;text&#x27; only supported
   * @return type
  **/
  @Schema(description = "Provide of watermark to be applied inside the 'type' key. For now only type 'text' only supported")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public WatermarkSettings orientation(OrientationEnum orientation) {
    this.orientation = orientation;
    return this;
  }

   /**
   * Orientation of watermark to be applied on the document
   * @return orientation
  **/
  @Schema(description = "Orientation of watermark to be applied on the document")
  public OrientationEnum getOrientation() {
    return orientation;
  }

  public void setOrientation(OrientationEnum orientation) {
    this.orientation = orientation;
  }

  public WatermarkSettings fontName(String fontName) {
    this.fontName = fontName;
    return this;
  }

   /**
   * Font name in which the watermark text needs to be applied on the output document.
   * @return fontName
  **/
  @Schema(example = "Arial", description = "Font name in which the watermark text needs to be applied on the output document.")
  public String getFontName() {
    return fontName;
  }

  public void setFontName(String fontName) {
    this.fontName = fontName;
  }

  public WatermarkSettings fontSize(Integer fontSize) {
    this.fontSize = fontSize;
    return this;
  }

   /**
   * Font size of the watermark text to be applied on the output document. Given size will be considered in inches.
   * minimum: 8
   * maximum: 144
   * @return fontSize
  **/
  @Schema(example = "16", description = "Font size of the watermark text to be applied on the output document. Given size will be considered in inches.")
  public Integer getFontSize() {
    return fontSize;
  }

  public void setFontSize(Integer fontSize) {
    this.fontSize = fontSize;
  }

  public WatermarkSettings fontColor(String fontColor) {
    this.fontColor = fontColor;
    return this;
  }

   /**
   * Font colour of the watermark text to be applied on the output document. Colours can be represented as &#x27;#04AB8F&#x27;. RGB format is also allowed.
   * @return fontColor
  **/
  @Schema(example = "#000000", description = "Font colour of the watermark text to be applied on the output document. Colours can be represented as '#04AB8F'. RGB format is also allowed.")
  public String getFontColor() {
    return fontColor;
  }

  public void setFontColor(String fontColor) {
    this.fontColor = fontColor;
  }

  public WatermarkSettings opacity(Integer opacity) {
    this.opacity = opacity;
    return this;
  }

   /**
   * Opacity value for watermark to be applied on the document
   * minimum: 0
   * maximum: 10
   * @return opacity
  **/
  @Schema(description = "Opacity value for watermark to be applied on the document")
  public Integer getOpacity() {
    return opacity;
  }

  public void setOpacity(Integer opacity) {
    this.opacity = opacity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WatermarkSettings watermarkSettings = (WatermarkSettings) o;
    return Objects.equals(this.text, watermarkSettings.text) &&
        Objects.equals(this.type, watermarkSettings.type) &&
        Objects.equals(this.orientation, watermarkSettings.orientation) &&
        Objects.equals(this.fontName, watermarkSettings.fontName) &&
        Objects.equals(this.fontSize, watermarkSettings.fontSize) &&
        Objects.equals(this.fontColor, watermarkSettings.fontColor) &&
        Objects.equals(this.opacity, watermarkSettings.opacity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, type, orientation, fontName, fontSize, fontColor, opacity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WatermarkSettings {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    orientation: ").append(toIndentedString(orientation)).append("\n");
    sb.append("    fontName: ").append(toIndentedString(fontName)).append("\n");
    sb.append("    fontSize: ").append(toIndentedString(fontSize)).append("\n");
    sb.append("    fontColor: ").append(toIndentedString(fontColor)).append("\n");
    sb.append("    opacity: ").append(toIndentedString(opacity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
