/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.WriterConvertionUnit;
import com.officeintegrator.model.WriterSupportedLanguages;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WriterEditorSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class WriterEditorSettings {
  @SerializedName("unit")
  private WriterConvertionUnit unit = null;

  @SerializedName("language")
  private WriterSupportedLanguages language = null;

  /**
   * pageview (&#x27;view&#x27; param is applicable to new documents only)
   */
  @JsonAdapter(ViewEnum.Adapter.class)
  public enum ViewEnum {
    WEBVIEW("webview"),
    PAGEVIEW("pageview");

    private String value;

    ViewEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static ViewEnum fromValue(String text) {
      for (ViewEnum b : ViewEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<ViewEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ViewEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ViewEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ViewEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("view")
  private ViewEnum view = ViewEnum.PAGEVIEW;

  public WriterEditorSettings unit(WriterConvertionUnit unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @Schema(description = "")
  public WriterConvertionUnit getUnit() {
    return unit;
  }

  public void setUnit(WriterConvertionUnit unit) {
    this.unit = unit;
  }

  public WriterEditorSettings language(WriterSupportedLanguages language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @Schema(description = "")
  public WriterSupportedLanguages getLanguage() {
    return language;
  }

  public void setLanguage(WriterSupportedLanguages language) {
    this.language = language;
  }

  public WriterEditorSettings view(ViewEnum view) {
    this.view = view;
    return this;
  }

   /**
   * pageview (&#x27;view&#x27; param is applicable to new documents only)
   * @return view
  **/
  @Schema(description = "pageview ('view' param is applicable to new documents only)")
  public ViewEnum getView() {
    return view;
  }

  public void setView(ViewEnum view) {
    this.view = view;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WriterEditorSettings writerEditorSettings = (WriterEditorSettings) o;
    return Objects.equals(this.unit, writerEditorSettings.unit) &&
        Objects.equals(this.language, writerEditorSettings.language) &&
        Objects.equals(this.view, writerEditorSettings.view);
  }

  @Override
  public int hashCode() {
    return Objects.hash(unit, language, view);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WriterEditorSettings {\n");
    
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    view: ").append(toIndentedString(view)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
