/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * WriterPermissions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class WriterPermissions {
  @SerializedName("document.export")
  private Boolean documentExport = true;

  @SerializedName("document.print")
  private Boolean documentPrint = true;

  @SerializedName("document.edit")
  private Boolean documentEdit = true;

  @SerializedName("review.comment")
  private Boolean reviewComment = false;

  @SerializedName("review.changes.resolve")
  private Boolean reviewChangesResolve = false;

  @SerializedName("collab.chat")
  private Boolean collabChat = true;

  @SerializedName("document.pausecollaboration")
  private Boolean documentPausecollaboration = false;

  @SerializedName("document.fill")
  private Boolean documentFill = true;

  public WriterPermissions documentExport(Boolean documentExport) {
    this.documentExport = documentExport;
    return this;
  }

   /**
   * To enable or disable document download option
   * @return documentExport
  **/
  @Schema(description = "To enable or disable document download option")
  public Boolean isDocumentExport() {
    return documentExport;
  }

  public void setDocumentExport(Boolean documentExport) {
    this.documentExport = documentExport;
  }

  public WriterPermissions documentPrint(Boolean documentPrint) {
    this.documentPrint = documentPrint;
    return this;
  }

   /**
   * To enable or disable document print option
   * @return documentPrint
  **/
  @Schema(description = "To enable or disable document print option")
  public Boolean isDocumentPrint() {
    return documentPrint;
  }

  public void setDocumentPrint(Boolean documentPrint) {
    this.documentPrint = documentPrint;
  }

  public WriterPermissions documentEdit(Boolean documentEdit) {
    this.documentEdit = documentEdit;
    return this;
  }

   /**
   * Provide option to allow edit access to the document
   * @return documentEdit
  **/
  @Schema(description = "Provide option to allow edit access to the document")
  public Boolean isDocumentEdit() {
    return documentEdit;
  }

  public void setDocumentEdit(Boolean documentEdit) {
    this.documentEdit = documentEdit;
  }

  public WriterPermissions reviewComment(Boolean reviewComment) {
    this.reviewComment = reviewComment;
    return this;
  }

   /**
   * Provide option to manage comments
   * @return reviewComment
  **/
  @Schema(description = "Provide option to manage comments")
  public Boolean isReviewComment() {
    return reviewComment;
  }

  public void setReviewComment(Boolean reviewComment) {
    this.reviewComment = reviewComment;
  }

  public WriterPermissions reviewChangesResolve(Boolean reviewChangesResolve) {
    this.reviewChangesResolve = reviewChangesResolve;
    return this;
  }

   /**
   * Provide option to resolve track changes
   * @return reviewChangesResolve
  **/
  @Schema(description = "Provide option to resolve track changes")
  public Boolean isReviewChangesResolve() {
    return reviewChangesResolve;
  }

  public void setReviewChangesResolve(Boolean reviewChangesResolve) {
    this.reviewChangesResolve = reviewChangesResolve;
  }

  public WriterPermissions collabChat(Boolean collabChat) {
    this.collabChat = collabChat;
    return this;
  }

   /**
   * To enable or disable chat panel for the collaborators
   * @return collabChat
  **/
  @Schema(description = "To enable or disable chat panel for the collaborators")
  public Boolean isCollabChat() {
    return collabChat;
  }

  public void setCollabChat(Boolean collabChat) {
    this.collabChat = collabChat;
  }

  public WriterPermissions documentPausecollaboration(Boolean documentPausecollaboration) {
    this.documentPausecollaboration = documentPausecollaboration;
    return this;
  }

   /**
   * Provide option to manage collaboration
   * @return documentPausecollaboration
  **/
  @Schema(description = "Provide option to manage collaboration")
  public Boolean isDocumentPausecollaboration() {
    return documentPausecollaboration;
  }

  public void setDocumentPausecollaboration(Boolean documentPausecollaboration) {
    this.documentPausecollaboration = documentPausecollaboration;
  }

  public WriterPermissions documentFill(Boolean documentFill) {
    this.documentFill = documentFill;
    return this;
  }

   /**
   * Provide option to allow edit access for the fillable fields
   * @return documentFill
  **/
  @Schema(description = "Provide option to allow edit access for the fillable fields")
  public Boolean isDocumentFill() {
    return documentFill;
  }

  public void setDocumentFill(Boolean documentFill) {
    this.documentFill = documentFill;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WriterPermissions writerPermissions = (WriterPermissions) o;
    return Objects.equals(this.documentExport, writerPermissions.documentExport) &&
        Objects.equals(this.documentPrint, writerPermissions.documentPrint) &&
        Objects.equals(this.documentEdit, writerPermissions.documentEdit) &&
        Objects.equals(this.reviewComment, writerPermissions.reviewComment) &&
        Objects.equals(this.reviewChangesResolve, writerPermissions.reviewChangesResolve) &&
        Objects.equals(this.collabChat, writerPermissions.collabChat) &&
        Objects.equals(this.documentPausecollaboration, writerPermissions.documentPausecollaboration) &&
        Objects.equals(this.documentFill, writerPermissions.documentFill);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentExport, documentPrint, documentEdit, reviewComment, reviewChangesResolve, collabChat, documentPausecollaboration, documentFill);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WriterPermissions {\n");
    
    sb.append("    documentExport: ").append(toIndentedString(documentExport)).append("\n");
    sb.append("    documentPrint: ").append(toIndentedString(documentPrint)).append("\n");
    sb.append("    documentEdit: ").append(toIndentedString(documentEdit)).append("\n");
    sb.append("    reviewComment: ").append(toIndentedString(reviewComment)).append("\n");
    sb.append("    reviewChangesResolve: ").append(toIndentedString(reviewChangesResolve)).append("\n");
    sb.append("    collabChat: ").append(toIndentedString(collabChat)).append("\n");
    sb.append("    documentPausecollaboration: ").append(toIndentedString(documentPausecollaboration)).append("\n");
    sb.append("    documentFill: ").append(toIndentedString(documentFill)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
