/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Document formats supported by Zoho Writer:   * &#x60;doc&#x60; - Microsoft Word Document   * &#x60;docx&#x60; - Microsoft Word Document 2010+   * &#x60;rtf&#x60; - Rich Text Format   * &#x60;odt&#x60; - OpenDocument Text   * &#x60;htm&#x60; - Hyper Text Markup   * &#x60;html&#x60; - Hyper Text Markup Language   * &#x60;txt&#x60; - Plain Text Document 
 */
@JsonAdapter(WriterSupportedFormats.Adapter.class)
public enum WriterSupportedFormats {
  DOC("doc"),
  DOCX("docx"),
  RTF("rtf"),
  ODT("odt"),
  HTM("htm"),
  HTML("html"),
  TXT("txt");

  private String value;

  WriterSupportedFormats(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WriterSupportedFormats fromValue(String text) {
    for (WriterSupportedFormats b : WriterSupportedFormats.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WriterSupportedFormats> {
    @Override
    public void write(final JsonWriter jsonWriter, final WriterSupportedFormats enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WriterSupportedFormats read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WriterSupportedFormats.fromValue(String.valueOf(value));
    }
  }
}
