/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Document merge export formats supported by Zoho Writer:   * &#x60;docx&#x60; - Microsoft Word Document 2010+   * &#x60;pdf&#x60; - PDF format 
 */
@JsonAdapter(WriterMergeExportFormat.Adapter.class)
public enum WriterMergeExportFormat {
  DOCX("docx"),
  PDF("pdf");

  private String value;

  WriterMergeExportFormat(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WriterMergeExportFormat fromValue(String text) {
    for (WriterMergeExportFormat b : WriterMergeExportFormat.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WriterMergeExportFormat> {
    @Override
    public void write(final JsonWriter jsonWriter, final WriterMergeExportFormat enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WriterMergeExportFormat read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WriterMergeExportFormat.fromValue(String.valueOf(value));
    }
  }
}
