/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.officeintegrator.model.WriterSupportedFormats;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * WriterCallbackSettings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-04-22T19:29:22.008+05:30[Asia/Kolkata]")
public class WriterCallbackSettings {
  @SerializedName("save_url")
  private String saveUrl = "";

  @SerializedName("save_format")
  private WriterSupportedFormats saveFormat = null;

  /**
   * Specify the http method in which the save request has to be triggered.
   */
  @JsonAdapter(HttpMethodTypeEnum.Adapter.class)
  public enum HttpMethodTypeEnum {
    POST("post"),
    PUT("put");

    private String value;

    HttpMethodTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static HttpMethodTypeEnum fromValue(String text) {
      for (HttpMethodTypeEnum b : HttpMethodTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<HttpMethodTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final HttpMethodTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public HttpMethodTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return HttpMethodTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }  @SerializedName("http_method_type")
  private HttpMethodTypeEnum httpMethodType = HttpMethodTypeEnum.POST;

  @SerializedName("retries")
  private Integer retries = 0;

  @SerializedName("timeout")
  private Integer timeout = 120000;

  @SerializedName("save_url_params")
  private Map<String, Object> saveUrlParams = null;

  public WriterCallbackSettings saveUrl(String saveUrl) {
    this.saveUrl = saveUrl;
    return this;
  }

   /**
   * Provide your server location to which the latest content needs to be pushed back when the &#x27;Save&#x27; is performed.
   * @return saveUrl
  **/
  @Schema(description = "Provide your server location to which the latest content needs to be pushed back when the 'Save' is performed.")
  public String getSaveUrl() {
    return saveUrl;
  }

  public void setSaveUrl(String saveUrl) {
    this.saveUrl = saveUrl;
  }

  public WriterCallbackSettings saveFormat(WriterSupportedFormats saveFormat) {
    this.saveFormat = saveFormat;
    return this;
  }

   /**
   * Get saveFormat
   * @return saveFormat
  **/
  @Schema(required = true, description = "")
  public WriterSupportedFormats getSaveFormat() {
    return saveFormat;
  }

  public void setSaveFormat(WriterSupportedFormats saveFormat) {
    this.saveFormat = saveFormat;
  }

  public WriterCallbackSettings httpMethodType(HttpMethodTypeEnum httpMethodType) {
    this.httpMethodType = httpMethodType;
    return this;
  }

   /**
   * Specify the http method in which the save request has to be triggered.
   * @return httpMethodType
  **/
  @Schema(description = "Specify the http method in which the save request has to be triggered.")
  public HttpMethodTypeEnum getHttpMethodType() {
    return httpMethodType;
  }

  public void setHttpMethodType(HttpMethodTypeEnum httpMethodType) {
    this.httpMethodType = httpMethodType;
  }

  public WriterCallbackSettings retries(Integer retries) {
    this.retries = retries;
    return this;
  }

   /**
   * Specify the number of retries required when the &#x27;Save&#x27; fails.
   * minimum: 0
   * maximum: 3
   * @return retries
  **/
  @Schema(description = "Specify the number of retries required when the 'Save' fails.")
  public Integer getRetries() {
    return retries;
  }

  public void setRetries(Integer retries) {
    this.retries = retries;
  }

  public WriterCallbackSettings timeout(Integer timeout) {
    this.timeout = timeout;
    return this;
  }

   /**
   * Specify the timeout for the given saveurl.
   * minimum: 30000
   * maximum: 120000
   * @return timeout
  **/
  @Schema(description = "Specify the timeout for the given saveurl.")
  public Integer getTimeout() {
    return timeout;
  }

  public void setTimeout(Integer timeout) {
    this.timeout = timeout;
  }

  public WriterCallbackSettings saveUrlParams(Map<String, Object> saveUrlParams) {
    this.saveUrlParams = saveUrlParams;
    return this;
  }

  public WriterCallbackSettings putSaveUrlParamsItem(String key, Object saveUrlParamsItem) {
    if (this.saveUrlParams == null) {
      this.saveUrlParams = new HashMap<String, Object>();
    }
    this.saveUrlParams.put(key, saveUrlParamsItem);
    return this;
  }

   /**
   * To customize the output parameters in which the document details will be pushed from our end.
   * @return saveUrlParams
  **/
  @Schema(example = "{\"file\":\"$content\",\"format\":\"$format\"}", description = "To customize the output parameters in which the document details will be pushed from our end.")
  public Map<String, Object> getSaveUrlParams() {
    return saveUrlParams;
  }

  public void setSaveUrlParams(Map<String, Object> saveUrlParams) {
    this.saveUrlParams = saveUrlParams;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WriterCallbackSettings writerCallbackSettings = (WriterCallbackSettings) o;
    return Objects.equals(this.saveUrl, writerCallbackSettings.saveUrl) &&
        Objects.equals(this.saveFormat, writerCallbackSettings.saveFormat) &&
        Objects.equals(this.httpMethodType, writerCallbackSettings.httpMethodType) &&
        Objects.equals(this.retries, writerCallbackSettings.retries) &&
        Objects.equals(this.timeout, writerCallbackSettings.timeout) &&
        Objects.equals(this.saveUrlParams, writerCallbackSettings.saveUrlParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saveUrl, saveFormat, httpMethodType, retries, timeout, saveUrlParams);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WriterCallbackSettings {\n");
    
    sb.append("    saveUrl: ").append(toIndentedString(saveUrl)).append("\n");
    sb.append("    saveFormat: ").append(toIndentedString(saveFormat)).append("\n");
    sb.append("    httpMethodType: ").append(toIndentedString(httpMethodType)).append("\n");
    sb.append("    retries: ").append(toIndentedString(retries)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    saveUrlParams: ").append(toIndentedString(saveUrlParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
