/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Convertion units supported by Zoho Writer:   * &#x60;in&#x60; - Unit in inches   * &#x60;mm&#x60; - Unit in millimeter 
 */
@JsonAdapter(WriterConvertionUnit.Adapter.class)
public enum WriterConvertionUnit {
  IN("in"),
  MM("mm");

  private String value;

  WriterConvertionUnit(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WriterConvertionUnit fromValue(String text) {
    for (WriterConvertionUnit b : WriterConvertionUnit.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WriterConvertionUnit> {
    @Override
    public void write(final JsonWriter jsonWriter, final WriterConvertionUnit enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WriterConvertionUnit read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WriterConvertionUnit.fromValue(String.valueOf(value));
    }
  }
}
