/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Languages supported by Zoho Writer:   * &#x60;en&#x60; - English   * &#x60;da&#x60; - Danish   * &#x60;de&#x60; - German   * &#x60;es&#x60; - Spanish   * &#x60;fr&#x60; - French   * &#x60;hu&#x60; - Hungarian   * &#x60;it&#x60; - Italian   * &#x60;ja&#x60; - Japanese   * &#x60;nl&#x60; - Dutch   * &#x60;pl&#x60; - Polish   * &#x60;pt&#x60; - Portuguese   * &#x60;ru&#x60; - Russian     * &#x60;sv&#x60; - Swedish   * &#x60;tr&#x60; - Turkish   * &#x60;zh&#x60; - Chinese   * &#x60;zh_CN&#x60; - Chinese/China     * &#x60;vi&#x60; - Vietnames   * &#x60;cs&#x60; - Czech   * &#x60;el&#x60; - Greek   * &#x60;et&#x60; - Estonian     * &#x60;fi&#x60; - Finnish   * &#x60;hr&#x60; - Croatian   * &#x60;ko&#x60; - Korean - [ko]   * &#x60;lt&#x60; - Lithuanian   * &#x60;sk&#x60; - Slovak   * &#x60;th&#x60; - Thai   * &#x60;uk&#x60; - Ukrainian     * &#x60;bg&#x60; - Bulgarian   * &#x60;ca&#x60; - Catalan   * &#x60;no&#x60; - KoreanNorwegian   * &#x60;ro&#x60; - Romanian   * &#x60;ar&#x60; - Arabic   * &#x60;iw&#x60; - Hebrew   * &#x60;ur&#x60; - Urdu &gt; externalDocs:     description: Find list of support language list     url: https://www.zoho.com/officeplatform/integrator/help/supported-languages.html 
 */
@JsonAdapter(WriterSupportedLanguages.Adapter.class)
public enum WriterSupportedLanguages {
  EN("en"),
  DA("da"),
  DE("de"),
  ES("es"),
  FR("fr"),
  HU("hu"),
  IT("it"),
  JA("ja"),
  NL("nl"),
  PL("pl"),
  PT("pt"),
  RU("ru"),
  SV("sv"),
  TR("tr"),
  ZH("zh"),
  ZH_CN("zh_CN"),
  VI("vi"),
  CS("cs"),
  EL("el"),
  ET("et"),
  FI("fi"),
  HR("hr"),
  KO("ko"),
  LT("lt"),
  SK("sk"),
  TH("th"),
  UK("uk"),
  BG("bg"),
  CA("ca"),
  FALSE("false"),
  RO("ro"),
  AR("ar"),
  IW("iw"),
  UR("ur");

  private String value;

  WriterSupportedLanguages(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WriterSupportedLanguages fromValue(String text) {
    for (WriterSupportedLanguages b : WriterSupportedLanguages.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WriterSupportedLanguages> {
    @Override
    public void write(final JsonWriter jsonWriter, final WriterSupportedLanguages enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WriterSupportedLanguages read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WriterSupportedLanguages.fromValue(String.valueOf(value));
    }
  }
}
