/*
 * Office Integrator
 * We've built Zoho Office Integrator for businesses that are building a web application of their own, but still need full-featured office editors to create, edit, and manage their documents. If you're a business with either of the following requirements, Zoho Office Integrator might just be perfect for you.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@officeapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.officeintegrator.auth;

import com.officeintegrator.Pair;

import java.util.Map;
import java.util.List;

public interface Authentication {
    /**
     * Apply authentication settings to header and query params.
     *
     * @param queryParams List of query parameters
     * @param headerParams Map of header parameters
     */
    void applyToParams(List<Pair> queryParams, Map<String, String> headerParams);
}
